### ISSUE TITLE
重复跳转登录页

### ISSUE THREAD

**Issue by Flipped321** [mteamwhy/mt-web-pre#100]
登录之后随便点几下登录就失效了，接口401，报登陆过期，退回到登陆页面，登陆后重复上述过程
![image](https://github.com/mteamwhy/mt-web-pre/assets/43898689/754d0801-1f2b-43b0-9d85-775d7e392e49)
红的都是401
![image](https://github.com/mteamwhy/mt-web-pre/assets/43898689/6c53e0db-baa6-4680-bda9-f48bcf629c51)

**Comment by worldyun** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/37605891/b64cb147-ec4b-444f-9bad-423f9e0e9cf0)
点击登录后，登录按钮一直loading，接口返回内容乱码

**Comment by worldyun** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/37605891/a67a9ae1-11dc-4fe1-b386-0af762456367)
login接口返回的auth信息，会在后续的接口中被清除
