### ISSUE TITLE
群晖无法使用RSS订阅下载

### ISSUE THREAD

**Issue by DaPoHou** [mteamwhy/mt-web-pre#114]
重新生成的rss订阅链接，仍然无法正常下载。

![捕获](https://github.com/mteamwhy/mt-web-pre/assets/26761596/7b1da4f2-751c-4bef-8d52-7e5edcd720ee)

**Comment by jianglin8-hub** [comment]
控制台，更换默认下载域名

**Comment by DaPoHou** [comment]
> 控制台，更换默认下载域名

这个就是更换后的。下载的文件名也不对

**Comment by jianglin8-hub** [comment]
> > 控制台，更换默认下载域名
> 
> 这个就是更换后的。下载的文件名也不对

更换后，可能要重新添加rss链接。（更换后，可以先在浏览器测试能否下载，浏览器不行 rss肯定也不行。）

文件名问题请联系群晖解决。（这是已知的但他们不修）

**Comment by DaPoHou** [comment]
> > > 控制台，更换默认下载域名
> > 
> > 
> > 这个就是更换后的。下载的文件名也不对
> 
> 更换后，可能要重新添加rss链接。（更换后，可以先在浏览器测试能否下载，浏览器不行 rss肯定也不行。）
> 
> 文件名问题请联系群晖解决。（这是已知的但他们不修）

肯定重新添加了rss订阅。
群晖无法下载种子文件是在m-team
去年某次服务器调整升级后出现的。
应该是和服务器环境配置有关。
群晖使用其他pt站没什么问题。

**Comment by mteamwhy** [comment]
此類問題請洽nas廠商,我們只能針對現有主流客戶端debug

**Comment by capesl** [comment]
这问题一直没解决方法吗？

**Comment by capesl** [comment]
@DaPoHou 后来有解决方法了吗？
