### ISSUE TITLE
关闭二级验证无果

### ISSUE THREAD

**Issue by zxf189** [mteamwhy/mt-web-pre#116]
网站改版后还得自行设置二级验证，所以重新设置，但没有把旧的验证器（google）删除，在新的验证器（google）上显示可把旧的验证器删除，删除旧的验证器后发现新的验证器出现两行验证码，所以把新的验证器删除（忘记应该先关闭），导致网站退出后无法进入。使用邮箱登入，能收到验证码，但填入号码后，点击登入，光标又自动在二级验证的小窗口里。经客服指导换浏览器和隐身模式，都不行。自我猜测，可能是开了两个相同平台otp的缘由

**Comment by jianglin8-hub** [comment]
截图看一下，另请附用户id

**Comment by zxf189** [comment]
今天上午在公司发现已经关闭二级验证，遂重新设置二级验证，经google OTP扫描后生成验证码，输入进去后点确定，但没反映，重新来过也不行。意味着OTP对网站生成了，但实际没开通。
现在只有公司电脑、手机能上，也不敢退出。

下午回到家，登陆网站，先用OTP不行，接着用邮箱也不行，无法登陆。











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mteamwhy/mt-web-pre"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mteamwhy/mt-web-pre] 关闭二级验证无果 (Issue #116)





 
截图看一下，另请附用户id

**Comment by zxf189** [comment]
截图在邮件里回复了，这里上来比较费劲
