### ISSUE TITLE
建议将成人区的预览图比例由5:7改为7:5

### ISSUE THREAD

**Issue by hzwei2017** [mteamwhy/mt-web-pre#12]
成人区大部分封面都是由两张图拼接而成的，现在的5:7居中预览模式，在不点开的前提下看不完全封面内容。
![Snipaste_2024-03-23_14-08-11](https://github.com/mteamwhy/mt-web-pre/assets/26561870/30c4601b-f362-4d78-b036-3877cceaa909)

**Comment by mteamwhy** [comment]
現在這麼小已無調整意義
