### ISSUE TITLE
目前做种数栏目添加一个容量数字

### ISSUE THREAD

**Issue by ccc-3po** [mteamwhy/mt-web-pre#121]
希望添加一个当前做种总数，例如 **目前做种（500GB，种子数量：10）** .
![image](https://github.com/mteamwhy/mt-web-pre/assets/44689813/2ff3fc0f-fd8b-459d-8e3f-2fccc8177e37)

**Comment by mteamwhy** [comment]
https://github.com/mteamwhy/mt-web-pre/issues/84
