### ISSUE TITLE
重置密鑰會導致下載種子失敗約15分鐘

### ISSUE THREAD

**Issue by kojuro-date** [mteamwhy/mt-web-pre#130]
透過控制台安全選項重置密鑰之後
大概會有10~15分鐘無法下載種子
會下載一個檔案link.json，然後內容為
```
{"message":"禁止訪問","data":null,"code":"1"}
```
15min後，會正常

**Comment by jianglin8-hub** [comment]
种子的下载链接从何处获取的，网页？ RSS？

**Comment by kojuro-date** [comment]
> 种子的下载链接从何处获取的，网页？ RSS？

從API獲取的

**Comment by jianglin8-hub** [comment]
> > 种子的下载链接从何处获取的，网页？ RSS？
> 
> 從API獲取的

重置后，通过API重新生成下载链接了吗
