### ISSUE TITLE
种子列表页副标题文字无法选中

### ISSUE THREAD

**Issue by a1zaza** [mteamwhy/mt-web-pre#133]
点击副标题中间部分无法选中
![image](https://github.com/mteamwhy/mt-web-pre/assets/121684999/60273676-d845-4511-8eb7-96807af08b57)

只能从结束的后面往前滑才可以选中
![image](https://github.com/mteamwhy/mt-web-pre/assets/121684999/8aa66fcf-9060-4c45-b62b-56e2735a0909)

**Comment by mteamwhy** [comment]
請問使用的瀏覽器,有辦法復現嗎

**Comment by a1zaza** [comment]
Chrome 最新版
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
稳定复现的，应该是页面上把副标题部分也当作链接的一部分了，是不是可以考虑只把主标题放在 <a> 标签下，副标题单纯作为文字显示
![image](https://github.com/mteamwhy/mt-web-pre/assets/121684999/63bab06d-2383-4e02-b08b-b1a0037877d5)

**Comment by jianglin8-hub** [comment]
fixed

**Comment by a1zaza** [comment]
感谢
