### ISSUE TITLE
发种子的时候无法选择“其他”选项

### ISSUE THREAD

**Issue by kasumises** [mteamwhy/mt-web-pre#134]
![v](https://github.com/mteamwhy/mt-web-pre/assets/165052074/307822e9-7841-44fd-b488-814c8c1bd614)

发种的时候，选择种子类型中，没有“其他”选项 昨天写了工单咨询，建议我更换浏览器，使用chorme浏览器 我换成了新浏览器之后，依然和原来一样，发布的时候，文件类型里面没有“其他”选项，如图 难道是我账号问题？？

电脑windows10 所有其他网站一切正常，升级之前一切正常，现在登录后无论如何在发布界面没有“其他”选项，导致无法发布文件。我主要发布教育类文件，没法选择其他的话，就无法发布

**Comment by mteamwhy** [comment]
確認bug

層級錯誤

暫時解決方法，開啟成人模式

**Comment by BlueSkyClouds** [comment]
fix
