### ISSUE TITLE
無法在站外關閉二級驗證

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#135]
![image](https://github.com/mteamwhy/mt-web-pre/assets/164606755/17329fed-e191-4b79-b8a8-93732e5424f9)

不會提示已成功關閉，在站內查看，確實處於未關閉的狀態。

![image](https://github.com/mteamwhy/mt-web-pre/assets/164606755/8c842ffe-f0c7-4641-9f85-6be5bd940d0a)

**Comment by mteamwhy** [comment]
功能關閉
