### ISSUE TITLE
種子詳情頁中,行為增加收藏按鈕

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#142]
![image](https://github.com/mteamwhy/mt-web-pre/assets/30530524/fc3ef535-0268-4e47-8427-0f0ddc6fa1af)

**Comment by BlueSkyClouds** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/0ece3527-8f15-48ce-bdd5-208588897185)
