### ISSUE TITLE
无法切换OTP动态验证码二级验证

### ISSUE THREAD

**Issue by ikelem0708** [mteamwhy/mt-web-pre#148]
请问一下 我想切换成用OTP来验证
但输入验证码后 无法按确定
是什么情况呢?
有尝试使用手机 电脑(chrome 及Microsoft Edge浏览器)
但确定按钮无法起到作用
反而都不输入验证码
会有报错的提示

**Comment by mteamwhy** [comment]
得看一下無法操作時的截圖

**Comment by BlueSkyClouds** [comment]
确认BUG 修复中

**Comment by BlueSkyClouds** [comment]
> ![IMG_5955](https://github.com/mteamwhy/mt-web-pre/assets/102024426/46fa898e-c690-410b-8db4-1212cc6a089a)
> 输入验证码后 确定怎么按都没反应

已修复

**Comment by ikelem0708** [comment]
![螢幕擷取畫面 2024-03-29 091051](https://github.com/mteamwhy/mt-web-pre/assets/102024426/f84c5210-bb68-4e2e-b53b-9ad341ee8e12)
您好 目前输入完正确验证码后 按正确有反应了 
但却是显示两部验证状态异常  请问后续要该如何处理呢?
