### ISSUE TITLE
死种判定错误。

### ISSUE THREAD

**Issue by AboutCXJ** [mteamwhy/mt-web-pre#149]
<img width="1366" alt="截屏2024-03-28 21 58 19" src="https://github.com/mteamwhy/mt-web-pre/assets/19811825/a997109b-23eb-462d-bf2c-6809efbbea8c">
选择了仅展示活跃种子，但是还是包含了很多死种，特别是这种，没出过种，也没人做种的。

**Comment by jianglin8-hub** [comment]
基于性能考虑，数据刷新存在延迟不能100%保证无死种

**Comment by AboutCXJ** [comment]
> 基于性能考虑，数据刷新存在延迟不能100%保证无死种

这个应该不是延迟导致的，我观察好几天了，这些种子大多是12年前发布的

**Comment by jianglin8-hub** [comment]
目前死种的判定是长时间 无人做种+无人下载
