### ISSUE TITLE
簡介區域存在字數限制

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#15]
簡介區域超出一定字數後，點擊上傳種子會直接報錯，但不提示具體什麼地方有問題。

應當增加文字上限。

且應在簡介框右下角增加字數上限提示.

**Comment by jianglin8-hub** [comment]
最起码，你得说明是哪个种子吧

**Comment by mteamwhy** [comment]
復現後重新報告
