### ISSUE TITLE
二級驗證無法正常開啟

### ISSUE THREAD

**Issue by judiw** [mteamwhy/mt-web-pre#154]
原本账号已开启二級驗證，升级后安全設定中的二級驗證默认选中“啟用密碼+郵箱驗證”，改为“啟用密碼+動態驗證碼二級驗證”后，确认啟用雙重認證时提示“兩步驗證已啟用，不能重複開通”。
此时原有 OTP 已在扫码后被覆盖，页面内也无法操作关闭或更新 OTP。
![1711721052934675](https://github.com/mteamwhy/mt-web-pre/assets/38564340/f7382825-66d6-4eb9-a2f3-3504caba9fcb)

**Comment by rinscr3003** [comment]
我遇到同样的问题。除 @judiw 描述的情况外，我还发现我的原有二级验证没有起作用，登录时并不会要求我输入动态验证码。

**Comment by judiw** [comment]
> 我遇到同样的问题。除 @judiw 描述的情况外，我还发现我的原有二级验证没有起作用，登录时并不会要求我输入动态验证码。

我这边是可以选择输入动态验证码，不过是升级之前绑定的那个 OTP

**Comment by BlueSkyClouds** [comment]
再试试呢

**Comment by BlueSkyClouds** [comment]
> 我遇到同样的问题。除 @judiw 描述的情况外，我还发现我的原有二级验证没有起作用，登录时并不会要求我输入动态验证码。

需要重新绑定

**Comment by rinscr3003** [comment]
> 再试试呢

fixed，感谢
