### ISSUE TITLE
浏览站内时切换页面就出线意外的应用程序错误!

### ISSUE THREAD

**Issue by 3261007520** [mteamwhy/mt-web-pre#155]
![bd8f6d47f0b05bb0368ac5303a83d3d](https://github.com/mteamwhy/mt-web-pre/assets/165464006/a4114bb4-ce2c-4255-9bb5-e1039e2dff54)
我录个了视频不知道怎么发，如果需要可以发邮箱

**Comment by 3261007520** [comment]
问题主要在切换英文和繁体然后翻译，在点其他页面就回出现这个情况

**Comment by mteamwhy** [comment]
插件問題導致
