### ISSUE TITLE
发种时演员一项无法输入

### ISSUE THREAD

**Issue by blackwink** [mteamwhy/mt-web-pre#156]
成人区发种选择输入演员姓名时，输入内容后再点击其他地方之前输入的内容消失，也无法像以前一样搜索和选择姓名。

**Comment by jianglin8-hub** [comment]
建议填写dmm，会自动关联

**Comment by BlueSkyClouds** [comment]
> 成人区发种选择输入演员姓名时，输入内容后再点击其他地方之前输入的内容消失，也无法像以前一样搜索和选择姓名。

再试试呢

**Comment by freedomlang** [comment]
> > 成人区发种选择输入演员姓名时，输入内容后再点击其他地方之前输入的内容消失，也无法像以前一样搜索和选择姓名。
> 
> 再试试呢

发布页的演员表单项屏蔽了
