### ISSUE TITLE
希望增加跨平台的BT客户端种类

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#157]
https://www.biglybt.com/
https://webtorrent.io/desktop/
bigly bt和webtorrent desktop，以上两个软件覆盖了从电脑Windows/Linux/Mac到安卓手机全平台的软件，peer id可以通过跟tixiati下载相同的bt种子点击对方客户端的国旗查看，如果网站实在不能支持，那就请支持一下安卓版utorrent8.x或者libretorrent3.4，其他手机软件要么不能下载64MB区块的种子要么已经几年不更新了，谢谢。

**Comment by jianglin8-hub** [comment]
v3.5已支持

**Comment by i990049** [comment]
> v3.5已支持

安卓手机版bigly bt是V3.4，麻烦也支持一下，谢谢

**Comment by jianglin8-hub** [comment]
> > v3.5已支持
> 
> 安卓手机版bigly bt是V3.4，麻烦也支持一下，谢谢

不考虑手机版
