### ISSUE TITLE
设为已读的按钮能不能移动到邮件上方？

### ISSUE THREAD

**Issue by trim21** [mteamwhy/mt-web-pre#160]
现在需要拉到最下面才能把邮件标记为已读，希望能直接在最上方设置已读。

![image](https://github.com/mteamwhy/mt-web-pre/assets/13553903/72744d65-4e4e-4704-8b2a-a9de9367e8a7)

**Comment by trim21** [comment]
最好能再加个全选

**Comment by BlueSkyClouds** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/fd896e5e-95c0-4144-8143-7af9254decc2)
这个就是全选

**Comment by BlueSkyClouds** [comment]
加上面，没找到合适的位置，或许把默认分页数据调低一点，就不需要滚动才显示删除如何？

**Comment by trim21** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/13553903/8360efca-2371-464a-a286-46768a5816ca)
放在这里？
