### ISSUE TITLE
变更种子标题获取方式

### ISSUE THREAD

**Issue by BlueSkyClouds** [mteamwhy/mt-web-pre#162]
see [trello](https://trello.com/c/9ceRfp5i/147-%E5%8F%91%E5%B8%83%E7%A7%8D%E5%AD%90-%E6%9C%AA%E8%AF%BB%E5%8F%96%E6%BA%90%E7%A7%8D%E5%AD%90%E5%91%BD%E5%90%8D?search_id=5a1021fc-3f34-48d8-83e7-83fd537d38eb)
因为如果用户转种会显示其他站的标题  如https://kp.m-team.cc/detail/769123

**Comment by jianglin8-hub** [comment]
发布未传 name 字段时，默认取torrent文件的主文件名，不会读取torrent file的info字段
此需求不做考虑。

**Comment by jianglin8-hub** [comment]
fixed
