### ISSUE TITLE
telegram bot 功能

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#177]
私人對話介面

1.綁定網站帳戶，網站同步顯示對應tg id
2.自我查詢基本訊息 - name/uid上傳/下載/分享率/魔力
3.站內短消息提示查看
4.查看現有波菜並提供下注功能

對應公開群顯示
1.有人下注波菜時訊息通知，應為
會員(不顯示名稱)下注 - 波菜名稱 - 選項 - 花費魔力
現魔力賠率為  選項1 賠率

2.提供現有波菜場次及選項，提供下注功能
直接群內@bot利用uid下注或是其他綁定方法

3.管理員查用bot查員該tg會員是否綁定網站，並私發訊息至管理員基本資料

4.新增波菜場次時通知

**Comment by mteamwhy** [comment]
功能
綁定tg後發送二步驗證碼(?)

**Comment by BlueSkyClouds** [comment]
功能
网站新增设置 发送系统通知至telegram  如分享率，登入通知等系统通知

**Comment by hahahaozi** [comment]
可在群内/私聊获取站内热种列表（仅供绑定用户） 24h内做种人数增长最多，24h内上传最多等

**Comment by jianglin8-hub** [comment]
done
