### ISSUE TITLE
封面无法正常加载

### ISSUE THREAD

**Issue by BlueSkyClouds** [mteamwhy/mt-web-pre#182]
部分种子在列表和打开种子封面无法加载，但有权限用户点击一次编辑后即可正常加载封面

**Comment by BlueSkyClouds** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/9f55d94b-b66b-44f5-b220-e5ad0204c668)
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/b50c13e5-92a4-43c0-b585-1e7efdfbe5f4)
点击编辑后
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/ca257a00-34a5-429a-9d93-4e3b3ec01bf2)
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/10ae414a-08fe-4312-8f80-7321741e872b)
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/658c9040-2d77-4a98-9061-ea09dec8324c)

**Comment by BlueSkyClouds** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/21595bb2-16e0-4b12-94e4-695f9704f2f2)
![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/fb0c426e-a063-453e-a53f-e4d3df5ebabb)

**Comment by jianglin8-hub** [comment]
douban会拦截外部域名访问。

**Comment by BlueSkyClouds** [comment]
> douban会拦截外部域名访问。

douban改成img1即可正常读取，不会拦截
