### ISSUE TITLE
純文字模式下的URL連結問題

### ISSUE THREAD

**Issue by MAN-GOR** [mteamwhy/mt-web-pre#201]
在「純文字模式」時，貼上從瀏覽器複製來的URL連結後，
它顯示的並不是純URL連結：「https\://kp.m-team.cc/detail/ID號碼」，
而是顯示帶藍色的網頁名稱：「[M-Team - TP :: 種子詳情 "種子名稱" - Powered by mTorrent](https://kp.m-team.cc/detail/ID號碼)」，
並且在切換至「Markdown模式」後，藍色就會消失不見：「M-Team - TP :: 種子詳情 "種子名稱" - Powered by mTorrent」。

理論上在純文字模式下應該是只會貼上純URL連結，而不是貼上網頁名稱？

**Comment by jianglin8-hub** [comment]
@freedomlang
