### ISSUE TITLE
大部分字幕无法下载

### ISSUE THREAD

**Issue by little6neko** [mteamwhy/mt-web-pre#203]
https://[kp.m-team.cc/api/subtitle/dl?id=55469](https://kp.m-team.cc/api/subtitle/dl?id=55469)
https://[kp.m-team.cc/api/subtitle/dl?id=55465](https://kp.m-team.cc/api/subtitle/dl?id=55465)
基本20小时前上传的字幕都无法下载
提示{"message":"檔案缺失，請聯系管理員","data":null,"code":"1"}

**Comment by BlueSkyClouds** [comment]
已做删除处理
