### ISSUE TITLE
无法发布种子，显示“上传失败”，没有具体原因

### ISSUE THREAD

**Issue by trim21** [mteamwhy/mt-web-pre#205]
![image](https://github.com/mteamwhy/mt-web-pre/assets/13553903/5b676c90-0ef7-4f1d-b678-93acdec6dda0)
![image_2024-04-09_00-57-38](https://github.com/mteamwhy/mt-web-pre/assets/13553903/48272157-c2cd-47a1-b856-b41a4a14474e)

**Comment by jianglin8-hub** [comment]
疑似种子内的文件名或路径太长

**Comment by trim21** [comment]
最长允许多长？

**Comment by jianglin8-hub** [comment]
路径+文件名。 不超过255字符

**Comment by trim21** [comment]
有可能是这个原因...

建议改一下错误提示（

**Comment by jianglin8-hub** [comment]
> 有可能是这个原因...
> 
> 建议改一下错误提示（

安全考虑，大多数错误信息是隐藏的。

**Comment by trim21** [comment]
> > 有可能是这个原因...
> > 建议改一下错误提示（
> 
> 安全考虑，大多数错误信息是隐藏的。

这个错误信息就没必要隐藏了吧...
