### ISSUE TITLE
种子搜索问题

### ISSUE THREAD

**Issue by worldYang** [mteamwhy/mt-web-pre#207]
我搜索种子时候不把全部标题写完（指完全匹配）就无法搜索到对应种子。详细见图
![Uploading AP~C_)JJV`E$7XP`6@3B2HT.png…]()

**Comment by worldYang** [comment]
![AP~C_)JJV`E$7XP`6@3B2HT](https://github.com/mteamwhy/mt-web-pre/assets/29117480/5780c784-94ef-4d6d-afef-33b650f6e9cf)

**Comment by mteamwhy** [comment]
完整的詞為單位，如blacksoulsii

**Comment by worldYang** [comment]
> 完整的詞為單位，如blacksoulsii

这样感觉寻找种子不方便。我如果只记得大致的种子名字，但不完整的名字就无法搜索到对应种子。
