### ISSUE TITLE
需要在種子頁面增加hash碼

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#21]
![image_2024-03-23_15-02-52](https://github.com/mteamwhy/mt-web-pre/assets/164606755/c8ffa066-3855-4a88-b691-a52c8f404e9e)

第三方工具需要該數據.

**Comment by jianglin8-hub** [comment]
取种子id吧

**Comment by trim21** [comment]
搜索结果里的`infoHash`字段也是空的

**Comment by mteamwhy** [comment]
暫不開放普通會員使用
