### ISSUE TITLE
AVS+视频编码无法识别mediainfo

### ISSUE THREAD

**Issue by WiN5551111** [mteamwhy/mt-web-pre#211]
目前potplayer和mediainfo两个软件都无法识别AVS+编码的视频，无法提供相应的mediainfo信息，但是现在发种要求必须按照标准添加MediaInfo，建议对AVS+编码的视频不硬性要求提供。
<img width="853" alt="屏幕截图 2024-04-10 234541" src="https://github.com/mteamwhy/mt-web-pre/assets/20541000/bf3e4a61-6a9f-4666-a3a7-0bcf5f7ef4c5">

**Comment by mteamwhy** [comment]
有相關種子嗎

**Comment by WiN5551111** [comment]
> 有相關種子嗎

https://kp.m-team.cc/detail/772695

**Comment by mteamwhy** [comment]
在mediainfo開放支持前不要求avs+的視頻提供
