### ISSUE TITLE
站免功能

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#212]
設置特定條件指定促銷功能
並加上提示通知
1.設定全站全部分類促銷，包含指定日期
2.設定特定小組促銷，包含指定日期

**Comment by mteamwhy** [comment]
結合專輯的部份應該優先如下

全站 > 專輯 > 小組 > 後台規則，前面三個結束後會回到後台規則

如種子20240412 促銷結束

全站於20240410開啟，20240414結束，結束時判斷後台規則，該種子已不再適用於後台的時限促銷

**Comment by jianglin8-hub** [comment]
“全站 > 專輯 > 小組 > 後台規則” 这个算法不太合理，

应当 FREE > 30% >50% （不应区分是 种子自身的促销 或者 全站促销）

**Comment by mteamwhy** [comment]
期限的問題應該參考慮舊np就行

我的想法是全站的促銷優先度要大於自定義規則的

**Comment by mteamwhy** [comment]
如同你講的free也是優於其他順位

**Comment by jianglin8-hub** [comment]
status 中增加 promotionRule 字段 （匹配的规则，折扣可能小于 种子自身的折扣，取最大促销显示）

/admin/promotion/rule/list

/admin/promotion/rule/add 
json 传参
categories  id数组
teams id数组
discount  （P30、P50、FREE）
startTime 开始时间
endTime 结束时间

/admin/promotion/rule/del
参数id
