### ISSUE TITLE
部分种子无法读取dmm链接

### ISSUE THREAD

**Issue by shichent** [mteamwhy/mt-web-pre#219]
IPVR-261: https://kp.m-team.cc/detail/773554
DSVR-1238: https://kp.m-team.cc/detail/761498
DSVR-555: https://kp.m-team.cc/detail/760354
NOSKN-021: https://kp.m-team.cc/detail/759126
KIWVR-418: https://kp.m-team.cc/detail/743239
MDVR-214: https://kp.m-team.cc/detail/742787

似乎问题在VR比较集中，如果搜VR的片子，只能搜到OVVR
![屏幕截图 2024-04-15 110046](https://github.com/mteamwhy/mt-web-pre/assets/136275892/9fac07ab-25bd-46c1-aacc-cc9d3845b1b1)

**Comment by mteamwhy** [comment]
這部份我們研究一下

主要是這部片子是在digital不在mono/dvd
但我們的路徑是以mono/dvd為主

**Comment by mteamwhy** [comment]
https://github.com/mteamwhy/mt-web-pre/issues/222

合併至此
