### ISSUE TITLE
时间显示问题

### ISSUE THREAD

**Issue by shichent** [mteamwhy/mt-web-pre#220]
如果电脑时区不是UTC+8的话，网站上种子发布时间，论坛帖子发表时间，菠菜截止时间等计算错误。比如刚发布的种子会显示“13小时内”。种子内做种下载者信息部分，最近汇报时间的显示也不正确。

**Comment by shichent** [comment]
可不可以和旧版一样，全部用服务器时间，而不是用电脑本地时间？

**Comment by BlueSkyClouds** [comment]
> 可不可以和旧版一样，全部用服务器时间，而不是用电脑本地时间？

国外用户怎么办？

**Comment by shichent** [comment]
> > 可不可以和旧版一样，全部用服务器时间，而不是用电脑本地时间？
> 
> 国外用户怎么办？

我想说的是，可以有两种解决办法：1. 所有时间都换算成电脑本地时间显示，包括菠菜截止时间，种子free截止时间之类 2. 所有时间都按UTC+8时间显示

当然1最好，但是修复难度会更大。从我自己使用体验出发，2也可以接受。
