### ISSUE TITLE
dmm更改搜索方式

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#222]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/e897302a-1531-45d3-8745-7a9211e5f81f)
更改為可輸入完整網址及番號搜索

**Comment by jianglin8-hub** [comment]
德国IP测试无法访问

**Comment by mteamwhy** [comment]
從關鍵字改為網址

**Comment by jianglin8-hub** [comment]
digital 的搜索链接是？

**Comment by mteamwhy** [comment]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/f22e5b35-279f-44cd-a888-a18f55d98ada)
更改為可輸入完整網址及番號搜索
