### ISSUE TITLE
求种采纳通知

### ISSUE THREAD

**Issue by BlueSkyClouds** [mteamwhy/mt-web-pre#226]
求种采纳后给种子发布者发送站内信通知，如果是管理员操作并且给求种发布人发送站内信通知

**Comment by jianglin8-hub** [comment]
@mteamwhy @BlueSkyClouds 目前采纳的奖励是发给 提交人，例如tid由管理员提交，则采纳奖励发给管理员。此需求与当前规则冲突（提交人未必是发种人）。

**Comment by jianglin8-hub** [comment]
done
