### ISSUE TITLE
credential 的种子无法连接到 tracker

### ISSUE THREAD

**Issue by torgelee** [mteamwhy/mt-web-pre#228]
credential 的种子无法连接到 tracker：
<img width="1100" alt="截屏2024-04-20 10 30 47" src="https://github.com/mteamwhy/mt-web-pre/assets/3311142/0a6dd64a-cb2f-49b4-94f1-ff1ce61d4886">
但是 passkey 的 tracker 是可以正常连接的：
<img width="1085" alt="截屏2024-04-20 10 33 00" src="https://github.com/mteamwhy/mt-web-pre/assets/3311142/124f254d-134f-4838-a88d-b4dd00a162b3">

请问这个是怎么回事？谢谢！

**Comment by shichent** [comment]
可能和做种域名有关，你换个.io结尾的做种域名再试试credential种子？

**Comment by torgelee** [comment]
> 可能和做种域名有关，你换个.io结尾的做种域名再试试credential种子？

改成 io 后可以连上，但是下载不了，感觉不是这个问题

**Comment by torgelee** [comment]
修改成 https://tracker.m-team.io/announce.php?passkey=* 就可以，但是 credential 就是不行。

**Comment by torgelee** [comment]
怎么没有更新呢？
