### ISSUE TITLE
希望擴展RSS的功能

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#23]
希望RSS可以多一个订阅免费种子的选项，并且支持biglybt/bitcomet/tixiati/webtorrent desktop下载，这些都是跨平台的软件

但是,免費多為限時,中間可能出現不可知的情況.故免費種子抓取功能當慎重.

**Comment by mteamwhy** [comment]
https://github.com/mteamwhy/mt-web-pre/issues/143
