### ISSUE TITLE
建议恢复旧版的“按完成数”和“做种数”排序及评分显示位置调整

### ISSUE THREAD

**Issue by DaPoHou** [mteamwhy/mt-web-pre#234]
1、在旧版页面中， “完成数”或“做种数”是分两列的，可以对当前页面种子列表按照 “完成数”或“做种数”进行升序、降序排列的，非常方便。 新版没有这个功能，非常不方便查看近期的热门资源。 建议可以恢复旧版的这两个功能。 

2、评分显示位置调整： 建议将豆瓣和imdb评分直接显示在资源标题的下面，或者和目前的“盒子规则”进行互换位置 这样可以很方便的一目了然，不用再转头去看。

**Comment by mteamwhy** [comment]
1.
本站所使用的np版本在排序時是依"所有"的種子進行排序
相關功能已於
https://xp.m-team.io/rankings
復現

2.
這涉及每人習慣問題，建議至插件區求助該功能
https://xp.m-team.io/forum/55

**Comment by DaPoHou** [comment]
现在的排行页面太笼统了。
比如我想查看当前页面的种子热度就没办法。
或者说想查看7天内的。这个功能对于筛选种子很有用。毕竟种子太多，又太杂。

**Comment by mteamwhy** [comment]
> 现在的排行页面太笼统了。
> 
> 比如我想查看当前页面的种子热度就没办法。
> 
> 或者说想查看7天内的。这个功能对于筛选种子很有用。毕竟种子太多，又太杂。

舊版中並沒有所謂的七天內最多排序功能
只有有史以來全部種子的排序

當前頁面的種子熱度是指?

**Comment by mteamwhy** [comment]
我大約懂你的意思了

要當前頁面雙排序

目前暫不支持此功能,舊版也沒有

可使用第三方工具看看有無符合需求

**Comment by DaPoHou** [comment]
我记得旧版种子发布时间、下载完成数和做种数是单独列显示的。当点击相应的列标题时，会对当前页面进行排序。
现在无法访问旧版，否则我会录屏传上来。

**Comment by mteamwhy** [comment]
> 我记得旧版种子发布时间、下载完成数和做种数是单独列显示的。当点击相应的列标题时，会对当前页面进行排序。
> 
> 现在无法访问旧版，否则我会录屏传上来。

所有的np系統都是這樣設計的,上傳/下載/完成數三者分開,可以參考其他站點

但排序時是依據所有的種子,例如該分類有5萬個種子,會對5萬種子排列

**Comment by mteamwhy** [comment]
場景1
無使用分類，種子頁面有1000頁
使用排序，將對1000頁的種子進行排序

場景2
使用分類，種子頁面有100頁
使用排序，將對100頁的種子進行排序

場景3
使用條件搜索，種子頁面有10頁
使用排序，將對10頁的種子進行排序

場景4
使用精準條件搜索，種子頁面有1頁
使用排序，將對1頁的種子進行排序

只有場景4的狀況才存在對當前頁面排序，因為只有1頁
