### ISSUE TITLE
RSS + API Key获取不到新发布的种子

### ISSUE THREAD

**Issue by iisrun** [mteamwhy/mt-web-pre#241]
我再通过python3代码，使用RSS + API Key的方式获取数据时发现获取到的种子都是很久之前发布的，而没有最新的免费种子，是还有其他获取方式，还是我的方法是错误的。

**Comment by jianglin8-hub** [comment]
调试时建议先去除 team 之类参数，种子发布时如果未选择，按此条件会匹配不到。

**Comment by iisrun** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/31065612/1d87289e-41c5-428b-a8f3-db8b828c72f9)
我使用QB的rss功能查看获取的资源，最新的数据是2023-12-13，再往下都是21年、17年、16年发布的资源了，感觉不是我代码的问题，RSS功能好像有点问题，这个我是使用的主站的RSS链接 https://kp.m-team.cc

**Comment by mteamwhy** [comment]
> ![image](https://private-user-images.githubusercontent.com/31065612/326728015-1d87289e-41c5-428b-a8f3-db8b828c72f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjY0MjUsIm5iZiI6MTcxNDQ2NjEyNSwicGF0aCI6Ii8zMTA2NTYxMi8zMjY3MjgwMTUtMWQ4NzI4OWUtNDFjNS00MjhiLWE4ZjMtZGI4YjgyOGM3MmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA4MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTZkY2FmY2Y4OGRjM2RjODVmOGZhOGNmNjljNzkxMzg4ZDI1YWQwNDgxY2EyMDk0YThhOTNiZDA5ZjlmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QXiSQ69uQ18oMKDo8UFnYku7xQRcjzheT9Guz-SKj3g) 我使用QB的rss功能查看获取的资源，最新的数据是2023-12-13，再往下都是21年、17年、16年发布的资源了，感觉不是我代码的问题，RSS功能好像有点问题，这个我是使用的主站的RSS链接 https://kp.m-team.cc

rss參數帶了啥?

**Comment by iisrun** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/31065612/b1bf0b7c-386e-473e-916f-c0746064a016)
我是这样生成的RSS，直接使用的生成的地址，没有自己添加参数。

**Comment by mteamwhy** [comment]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/aceb336d-aee0-4918-8e73-f8c2b9720623)

按照你的參數我產生的好像沒問題?

**Comment by iisrun** [comment]
你用的哪个主站的域名创建的rss链接，我用和你一样的再试试，好奇怪的问题

**Comment by mteamwhy** [comment]
最後都會302回去主域名才對，用哪個都行，或是你站內管理組報告一下你所使用的rss完整連結

**Comment by iisrun** [comment]
好的，我试试  Thank you！
