### ISSUE TITLE
搜索底下使用團隊分類分級失效

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#25]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/3e697421-88d5-40df-b0aa-db05eaa3f7ec)

**Comment by jianglin8-hub** [comment]
此情况原因在于老数据，部分字段从未进行设置导致。

方案1：未设置 的不做匹配
方案2：未设置视为统配

当前结果页是方案2，你期望如何调整。
注：同步影响RSS

**Comment by mteamwhy** [comment]
> 此情况原因在于老数据，部分字段从未进行设置导致。
> 
> 
> 
> 方案1：未设置 的不做匹配
> 
> 方案2：未设置视为统配
> 
> 
> 
> 当前结果页是方案2，你期望如何调整。
> 
> 注：同步影响RSS

由於標題的適配性
是否可用搜索標題的方式列出結果，再通過sql一同修改?
例如標題含有Catedu的種子的團隊全設為Catedu

**Comment by mteamwhy** [comment]
https://github.com/mteamwhy/mt-web-pre/issues/141
