### ISSUE TITLE
菠菜頻道 刪除並退款 按钮点击 确定后没反应

### ISSUE THREAD

**Issue by jdianing** [mteamwhy/mt-web-pre#253]
2024-05-03 03:00:00 | 欧联杯半决赛首回合 马赛 VS 亚特兰大 | 常规时间，不含加时赛点球 | 已結束 | 編輯 刪除 刪除並退款

比赛走盘，刪除並退款 按钮点击 确定后没反应，麻烦看看什么原因，谢谢。

**Comment by jdianing** [comment]
另外开盘选择当天时间还是有问题，分钟只能选目前时间之后的。
![shijianwt](https://github.com/mteamwhy/mt-web-pre/assets/167783732/31f86394-50e8-421b-9a5c-9a08afacd76c)

**Comment by mteamwhy** [comment]
> 另外开盘选择当天时间还是有问题，分钟只能选目前时间之后的。 ![shijianwt](https://private-user-images.githubusercontent.com/167783732/327652532-31f86394-50e8-421b-9a5c-9a08afacd76c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTg0NTYsIm5iZiI6MTcxNDcxODE1NiwicGF0aCI6Ii8xNjc3ODM3MzIvMzI3NjUyNTMyLTMxZjg2Mzk0LTUwZTgtNDIxYi05YTVjLTlhMDhhZmFjZDc2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNjM1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzZkNjFlMmRjZWY2NTQ4M2VmODU5MmYxM2M1OWY4ZWJlYmRiNGYzYmZkNWJlMzEwMmQ5M2I5N2QyNzg2OGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TDzqcvb_tk3dpRyEl4t3Ap41PTbilQFgIQDH6jIc7vQ)

不是很懂這個，有需要選目前時間之前的?

**Comment by jdianing** [comment]
假设现在时间是中午12：22，需要开盘的的截止时间是晚上22：00，分钟不能选0--22分，只能选23--59分，明白什么意思吧？

**Comment by mteamwhy** [comment]
> 假设现在时间是中午12：22，需要开盘的的截止时间是晚上22：00，分钟不能选0--22分，只能选23--59分，明白什么意思吧？

往前一小時呢?

**Comment by BlueSkyClouds** [comment]
> > 假设现在时间是中午12：22，需要开盘的的截止时间是晚上22：00，分钟不能选0--22分，只能选23--59分，明白什么意思吧？
> 
> 往前一小時呢?

确认是bug，问题就是如果截止时间是当天，比如当前时间18:50  开盘时间 时间选19点，而分钟就只能选择50分以后的，第二天是正常。
