### ISSUE TITLE
跨平台下载软件更新

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#254]
跨平台下载软件更新
软件名字：BIGLY BT
版本号：3.6.0.0
https://github.com/BiglySoftware/BiglyBT/releases

软件名字：webtorrent desktop，对热种可以用VLC边看边下载
版本号：0.24.0
https://webtorrent.io/desktop/
以上两个软件覆盖了从电脑Windows/Linux/Mac到安卓手机全平台的软件，peer id可以通过跟tixiati下载相同的bt种子点击对方客户端的国旗查看。

**Comment by mteamwhy** [comment]
最新版本尚不支持
