### ISSUE TITLE
該種子不能被搜索

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#258]
https://kp.m-team.cc/detail/781148

原標題
Man.With.A.Plan.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
修改後
Man With A Plan S01 1080p AMZN WEB-DL DDP5.1 H.264-NTb

**Comment by mteamwhy** [comment]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/0f49d4f4-734b-4944-80b4-d48a19e6d865)
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/c07f6932-7d0d-4304-9395-1af7f002d874)

分詞問題待修

**Comment by jianglin8-hub** [comment]
done
