### ISSUE TITLE
论坛帖子无法编辑，编辑返回代码报错

### ISSUE THREAD

**Issue by Hamsterwe** [mteamwhy/mt-web-pre#262]
![image](https://github.com/mteamwhy/mt-web-pre/assets/124116916/1182bf5b-8117-40b3-89d9-313c1c4eb97f)

**Comment by Hamsterwe** [comment]
![Uploading 11.jpg…]()
![image](https://github.com/mteamwhy/mt-web-pre/assets/124116916/e577f680-3fa0-4e16-ba01-3caffe77f682)

**Comment by jianglin8-hub** [comment]
停用第三方插件、脚本
