### ISSUE TITLE
种子页面已去时间显示不对

### ISSUE THREAD

**Issue by shichent** [mteamwhy/mt-web-pre#263]
非UTC+8时区下，种子页面显示的已去时间/剩余时间显示不对。同一时刻发布的论坛帖子/种子，显示的种子发布已去时间比论坛帖子发布已去时间提前3小时。我记得几天前种子和论坛帖子还是一致的，应该是最近几天才出现的。

这下用油猴脚本都不知道怎么改了...

**Comment by mteamwhy** [comment]
麻煩貼個例子

**Comment by shichent** [comment]
> 麻煩貼個例子

![屏幕截图 2024-05-16 010500](https://github.com/mteamwhy/mt-web-pre/assets/136275892/04e24115-46ea-43d4-949c-49a5aef76d18)

截图时没有启用脚本。论坛同一帖，点开前后显示时间不同。种子发布的已去时间类似图中下面。

调节电脑本地时区应该就能复现

**Comment by shichent** [comment]
@mteamwhy 

现在情况是这样：有一些页面（比如菠菜）直接读取本地时间当作北京时间，另一些页面（比如种子首页）会读取本地时间并尝试转换为北京时间，但是这个转换有bug：如果电脑本地时间在东半球（UTC +X），网站会转换成UTC+8；如果本地时间在西半球（UTC-X），网站会转换成 UTC+(8-2X) 并当成北京时间。

我猜测问题应该出在：转换时间时是先转换成UTC再转换成北京时间，但是转换成UTC时是直接减去距离UTC的小时数，没有考虑到东西半球情况不一样，西半球应该是加上而不是减去。

我的诉求是：如果能全部改正最好，不能的话，可不可以至少保证所有的时间用相同方式处理，这样我至少可以用油猴脚本转换时间。

**Comment by i990049** [comment]
可以参考外国的XBTT和U232架构加入时区设置功能，我注册的那些外国的PT站点默认都是欧美时间，可以在注册的时候只接选择东八区GMT+8，看他们的网站就是用北京时间显示
