### ISSUE TITLE
请适配WebTorrent Desktop和新旧bigly bt客户端

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#265]
WebTorrent Desktop v0.24.0
https://webtorrent.io/desktop/
Client
WebTorrent/0.108.6 (https://webtorrent.io)
peer id
-WD0024-xxxxxxxxxxxx
BiglyBT 3.X版
https://github.com/BiglySoftware/BiglyBT/releases
Client
BiglyBT 3.4.0.0
peer_id=-BI3400-xxxxxxxxxxxx
Client
BiglyBT 3.6.0.0
peer_id=-BI3600-xxxxxxxxxxxx
以上12个X为英文和数字的通配符，如果新架构支持正则表达，建议自动支持3.x系列，免去后续升级适配，谢谢

**Comment by jianglin8-hub** [comment]
需提供 agent、peer_id

**Comment by i990049** [comment]
> 需提供 agent、peer_id

已提供

**Comment by mteamwhy** [comment]
不支持WebTorrent Desktop

**Comment by mteamwhy** [comment]
> 需提供 agent、peer_id

直接支持bigly 3.x吧

**Comment by i990049** [comment]
> > 需提供 agent、peer_id
> 
> 直接支持bigly 3.x吧

上面的client接下来的一行就是agent，可以改成通配符，以下x为通配符
BiglyBT 3.x.x.x
peer_id=-BI3xxx-xxxxxxxxxxxx

**Comment by jianglin8-hub** [comment]
3.5.x、3.6.x 已支持。
