### ISSUE TITLE
魔力明細頁面

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#266]
將做種積分及別人贈送的魔力加入相關種子tid

**Comment by jianglin8-hub** [comment]
做种积分记录种子ID明细不可行   数据量太大。

目前单用户做种峰值5w

**Comment by mteamwhy** [comment]
> 做种积分记录种子ID明细不可行 数据量太大。
> 
> 目前单用户做种峰值5w

那把贈送的魔力的加上吧

**Comment by jianglin8-hub** [comment]
> > 做种积分记录种子ID明细不可行 数据量太大。
> > 目前单用户做种峰值5w
> 
> 那把贈送的魔力的加上吧

加了，新记录会显示
