### ISSUE TITLE
發佈最近訊息時自動全站系統短信通知

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#268]
發佈首頁的最近訊息時自動全站系統短信通知

**Comment by mteamwhy** [comment]
PS：是否強制跳轉閱讀?

**Comment by jianglin8-hub** [comment]
同时发送系统消息，这个增加一个 可选项 吧

强制跳转 或者 悬浮的强提醒 可以做到

包括系统消息也可以强提醒。

**Comment by jianglin8-hub** [comment]
@freedomlang /admin/news/post 接口增加 andSendPM 参数，可选项，选中时 andSendPM = true

**Comment by mteamwhy** [comment]
最近訊息 - 強制跳轉
系統消息不處理
