### ISSUE TITLE
根據mediainfo資訊來指向基本資訊

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#272]
基本資訊
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/523c9362-e4e8-44ce-b70f-f31af70d1112)

視頻編碼(依Format)
AVC = H.264
HEVC = H.265
xvid = xvid
AV1 = AV1
MPEG Video = MPEG 2
VC-1 Video = VC1

音頻
Format的部份
MLP FBA 16-ch = TrueHD Atmos
MLP FBA = TrueHD
DTS XLL = DTS-HD MA
DTS = DTS
AC-3 = DD
E-AC-3 JOC = DDP / Atmos
E-AC-3 = DDP
AAC LC = AAC
FLAC = FLAC

解析度
依Width大小
1920 不管有沒有Scan type = 1080P
1920且Scan type為interlaced = 1080i
3840 = 4k
720 = 720P
不在以上 = SD

沒有就沒法判斷了，因為有些影片壓制時沒加上

**Comment by mteamwhy** [comment]
地區定位問題

特定分類發佈隱藏此欄位防止會員亂選
利用imdb/douban提供的國家自動定位
選單內建中英對照，輸入框可輸入中或英

新的方式見下圖

**Comment by mteamwhy** [comment]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/8add3fe6-f248-4a74-a837-03bfa98ff664)

![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/5b5acb62-272d-4dc9-a4ce-0d744d32b762)

**Comment by mteamwhy** [comment]
複選
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/ccb829ff-f3ae-4b9a-9f48-67b13c1523a4)

**Comment by mteamwhy** [comment]
音頻存在多音頻的問題，所以有優先權
高碼率優先顯示

音頻
MLP FBA 16-ch = TrueHD Atmos
MLP FBA = TrueHD
DTS XLL = DTS-HD MA
E-AC-3 JOC = E-AC-3 / Atmos
E-AC-3 = E-AC-3
DTS = DTS
AC-3 = AC-3
AAC LC = AAC
FLAC = FLAC

**Comment by jianglin8-hub** [comment]
@freedomlang 发布、详情、搜索 接口已增加 countries 字段

发布接口须字符串，以逗号分隔

**Comment by mteamwhy** [comment]
視頻編碼更新，請見首篇，把bluray的特別分類取消，併入現行

還有bdinfo 的無法識別

**Comment by mteamwhy** [comment]
解析度增加8k選項
7680 = 8k

**Comment by mteamwhy** [comment]
bdinfo的音頻部份

DTS-HD Master Audio          = DTS-HD MA
Dolby TrueHD/Atmos Audio = TrueHD Atmos
Dolby Digital Audio              = AC3(DD)
Dolby TrueHD Audio            = TrueHD
LPCM Audio                         = LPCM
