### ISSUE TITLE
種子發佈頁內的基本資訊未按尚排序排列

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#278]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/f6255ebf-e464-491b-90d4-b4b96f018f68)

如視頻參數、音頻參數，未按照後台設定的排序排列

![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/9f38e02d-1137-4b26-bea5-79112ef69296)

**Comment by jianglin8-hub** [comment]
接口响应顺序正确，前端看一下。
