### ISSUE TITLE
登录时真人验证永远失败

### ISSUE THREAD

**Issue by yuhaoxin** [mteamwhy/mt-web-pre#279]
![image](https://github.com/mteamwhy/mt-web-pre/assets/11943130/77b8c7c4-3bae-49a1-b977-9f177693a744)

**Comment by jianglin8-hub** [comment]
使用代理/VPN？
浏览器插件屏蔽内容？
推荐使用Chrome浏览器。

**Comment by yuhaoxin** [comment]
> 使用代理/VPN？ 浏览器插件屏蔽内容？ 推荐使用Chrome浏览器。

使用软路由VPN翻墙，浏览器安装了ublock插件，仅屏蔽广告，使用的edge浏览器。
但是同样的wifi环境下，使用iphone的safari没问题。

**Comment by yuhaoxin** [comment]
解决了，是youtube广告拦截插件的问题。
