### ISSUE TITLE
种子下载页面同伴客户端显示异常

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#281]
相同的分辨率，不同的站点，其他站点显示没问题
[url=https://smms.app/image/tfxMmpS2lD51RuZ][img]https://s2.loli.net/2024/06/01/tfxMmpS2lD51RuZ.png[/img][/url]
[url=https://smms.app/image/fDQXe2S4J16U9sc][img]https://s2.loli.net/2024/06/01/fDQXe2S4J16U9sc.png[/img][/url]

**Comment by mteamwhy** [comment]
看不了圖片

**Comment by i990049** [comment]
> 看不了圖片

https://wwi.lanzoup.com/i0IwD20hhs5a

**Comment by mteamwhy** [comment]
還是解析度的問題，目前在20~22吋上用1080看是正常的，但是我用notebook 13吋的確有你這問題

**Comment by i990049** [comment]
> 還是解析度的問題，目前在20~22吋上用1080看是正常的，但是我用notebook 13吋的確有你這問題

https://s21.ax1x.com/2024/06/05/pkYp1uq.png
我用的是ThinkPad和安卓手机，看过几十个国内外站点的peer列表，只有新馒头架构有问题

**Comment by guitarbug** [comment]
有相同的问题, 我现在规避的解决办法是把浏览器缩放至80%
