### ISSUE TITLE
论坛回帖中无法上传图片

### ISSUE THREAD

**Issue by abagaile** [mteamwhy/mt-web-pre#283]
论坛回帖中上传过一张图片，编辑的过程中触控板滑了，点了一下前进，离开了编辑页面，回到页面后编辑区被清空了，这时再上传相同的图片无法上传，尝试过改文件名，清空缓存并硬重载页面，都不行，裁剪后重新上传就可以了。猜测是图床不接受重复文件，但是上传之后并不会回显之前上传的图片地址是什么。
![CleanShot 2024-06-05 at 11 11 34@2x](https://github.com/mteamwhy/mt-web-pre/assets/143052568/56ebc866-c5ea-44ab-acc2-eaa7bf59ccb4)

**Comment by mteamwhy** [comment]
之前上傳的如果沒有存檔丟失是無法找回的

**Comment by abagaile** [comment]
无法找回但是应该允许重新上传吧

**Comment by mteamwhy** [comment]
原系統設定是24小時後，現已關閉
