### ISSUE TITLE
圖片插入後無立即顯示

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#284]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/002f3cb2-e6e7-45a8-b612-0b196a8afcf7)

**Comment by mteamwhy** [comment]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/3f9f0cd8-1549-474c-af40-7488a00c2adb)

利用這個連結插入的反而正常

**Comment by jianglin8-hub** [comment]
fixed
