### ISSUE TITLE
站免魔力池及魔力兌換功能增加

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#286]
魔力池：
用戶投入魔力至池中達一定數值，開啟全站免費(3天)，每月僅能開啟一次。
數值係數 = 自定

單種子全站免費(3天)：
魔力消耗 = 基本係數 x GB(不足1G等同1G) x 時間係數 x 做種人數係數

queued
每天最多10個種子同時促銷，超出的種子排入隊列，同時提供隊列表供查看

基本係數(待研究)
10000

時間係數
發佈日期在30天之內不允許
第31天起算 x2
每24天 -0.1
最少不於低0.5

做種人數係數
做種人數
≥100 x5
99-50 x3
49-30 x2
30-11 x1
10以下 x0.5

**Comment by mteamwhy** [comment]
隊列頁面
顯示
torrent id / 標題 / 預計促銷時間

已進行的銷促丟到庫存頁

**Comment by i990049** [comment]
相比全站免费，我还是更喜欢nexusphp的置顶促销插件，全站免费不一定能在几天内下载完孤种，置顶促销就可以，希望新架构可以加入置顶促销插件，谢谢。
