### ISSUE TITLE
調整字幕文件在種子詳情的顯示

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#287]
不同的種子如果是相同的imdb id，則該種子會顯示所有上傳到相同imdb的所有字幕

舊版有此功能

**Comment by jianglin8-hub** [comment]
@jakecreates1 这个已经好了，你不用处理

**Comment by jianglin8-hub** [comment]
@mteamwhy 仅电影所属类目按此处理。
