### ISSUE TITLE
個人詳情頁中的發布/做種....etc另彈出頁面

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#293]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/3af70814-f967-4223-bcb0-b5822e3ffd4e)

原先在原頁面展開，

改成彈出獨立頁面

樣式參考
/browse

表格為：
類別	標題	活動	上傳量	下載量	分享率

**Comment by mteamwhy** [comment]
@jakecreates1 
![image](https://github.com/mteamwhy/mt-web-pre/assets/30530524/93a1e40b-0ad0-4bb7-8468-577e6b6bd638)

往左移一點，有時會誤按

**Comment by jstvn** [comment]
> @jakecreates1 ![image](https://private-user-images.githubusercontent.com/30530524/338930763-93a1e40b-0ad0-4bb7-8468-577e6b6bd638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODg4MTMsIm5iZiI6MTcxODE4ODUxMywicGF0aCI6Ii8zMDUzMDUyNC8zMzg5MzA3NjMtOTNhMWU0MGItMGFkMC00YmI3LTg0NjgtNTc3ZTZiNmJkNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEwMzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODRmMGJlOTg3MTk5Yjc4MzJjNWVmYWIyOTQzZmY4ZTJiMzA3MWNhYzA2MjExZmFhNjEyODMyMWQ5OTE2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w3Ze_ZT0yyJdcUugvQrjXZqZiKbbl8jt9btKn7GpH3Y)
> 
> 往左移一點，有時會誤按

好的
