### ISSUE TITLE
「Markdown預覽編輯模式」下的換行問題

### ISSUE THREAD

**Issue by MAN-GOR** [mteamwhy/mt-web-pre#294]
在「Markdown預覽編輯模式」下的換行，在最終發佈時一次換行會變成兩次換行，造成排版錯誤。
例如輸入的文字是：
「
片名：…
譯名：…
年份：…
類型：…
演員：…
」
最終發佈時會變成：
「
片名：…

譯名：…

年份：…

類型：…

演員：…
」

「純文字模式」則無此問題。

**Comment by jianglin8-hub** [comment]
Markdown預覽模式：
1.从外部粘贴内容
2.切换code模式，再切换回预览模式，此时内容会出现空白行
