### ISSUE TITLE
站点无法识别缩略图链接

### ISSUE THREAD

**Issue by Digital1080** [mteamwhy/mt-web-pre#299]
mt站点无法正确识别缩略图链接， 可以正常上传小图链接，但是点开后无法指向大图链接。

例：BBCode链接内容

1. 原图（链接）[img]https://img.picgo.net/2024/06/14/zuken_chinesedress_03640f4b382083be6b9.jpg[/img]    
（可以正确识别，也是当前的预览图呈现方式）

2. 缩略图（链接）[url=https://www.picgo.net/image/%E6%9F%98%E7%83%9Fzuken-chinesedress-036.SDgibJ] 
                             [img]https://img.picgo.net/2024/06/14/zuken_chinesedress_03640f4b382083be6b9.th.jpg[/img][/url]

3.这里会额外指定个预览大图的链接，但是咱们站点不能识别，导致缩略图异常，经测试SDgibj的链接是预览图链接，也可以正常访问，但是在其它站点测试，会单独打开图床才能看到，我只想在当前站点打开。

4.很多图床都是这种2条链接形式

5.我看咱们站点DMM信息预览图是正常的，点击后会弹出大图预览；辛苦工作人员可以排查下，有些资源确实需要上传很多图，如果只是原图预览看着太大了，也不美观。

6.想实现效果: https://kp.m-team.cc/detail/792804   DMM的预览图
[https://img.picgo.net/2024/06/14/Snipaste_2024-06-14_21-29-596c69682d3d2e2ad3.png](url)

7.例 https://kp.m-team.cc/detail/792899    有问题的帖子

总结：只想实现点开缩略图，是大图效果

如有打扰实属无奈，请谅解

**Comment by mteamwhy** [comment]
`缩略图（链接）[url=https://www.picgo.net/image/%E6%9F%98%E7%83%9Fzuken-chinesedress-036.SDgibJ]
[img][https://img.picgo.net/2024/06/14/zuken_chinesedress_03640f4b382083be6b9.th.jpg[/img][/url]](https://img.picgo.net/2024/06/14/zuken_chinesedress_03640f4b382083be6b9.th.jpg%5B/img%5D%5B/url%5D)`

連結這兩個字的意思就是會跳轉到它的連結，不想要跳轉就不要帶連結

**Comment by Digital1080** [comment]
抱歉，我可能问的多，没描述清楚。

我想问的是，该如何实现发资源的时候，可以设置成小的预览图，并且打开后是张大图。
（现在只能上传大图链接，有些图床缩略图是.th.jpg格式，并不能打开大图）

如下图：
![01](https://github.com/mteamwhy/mt-web-pre/assets/109922594/eefbf3b6-e5d7-4684-a578-aca871d3fcb9)
![02](https://github.com/mteamwhy/mt-web-pre/assets/109922594/1785680c-44e5-4ed4-bf12-e2980d741579)

（我并不是编程人员，也许这个问题可能问的不专业）

**Comment by BlueSkyClouds** [comment]
> 有些图床缩略图是.th.jpg格式，并不能打开大图）

现在这样不就是？  img指定的是显示链接 而URL指定的是点击跳转链接

**Comment by Digital1080** [comment]
现在的大图链接，反正至少显示的是大图，如果要上传几十张图站的位置太多了；

有办法像DMM这样显示吗：
![03](https://github.com/mteamwhy/mt-web-pre/assets/109922594/b6e5cc19-f39a-4c80-8a48-f1ebc9e5f392)
