### ISSUE TITLE
黃星做種魔力翻倍疑似失效

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#3]
相關用戶id
308413

**Comment by dhasjsdksdksa** [comment]
相关用户id
192051

**Comment by ice7mo** [comment]
相關用戶id
320213

**Comment by ghouleztt** [comment]
永久vip黄星消失，同时做种魔力翻倍失效，用户id：288324

**Comment by BlueSkyClouds** [comment]
> 永久vip黄星消失，同时做种魔力翻倍失效，用户id：288324

没有黄星肯定就是实现状态，目前问题应该是部分用户黄星消失
