### ISSUE TITLE
非北京时区下，部分时间仍按照北京时间显示

### ISSUE THREAD

**Issue by shichent** [mteamwhy/mt-web-pre#300]
首先感谢修复非北京时区的时间显示问题。

我注意到，部分时间显示仍为北京时间，具体为：个人信息页的最近动向以及魔力值明细，种子促销截止时间以及盒子规则截止时间

**Comment by shichent** [comment]
又发现几个比较隐蔽的北京时间还没有改过来：菠菜的用户投注时间，种子完成详情的完成时间和最近活动时间处鼠标悬浮显示的时间

**Comment by jstvn** [comment]
> 又发现几个比较隐蔽的北京时间还没有改过来：菠菜的用户投注时间，种子完成详情的完成时间和最近活动时间处鼠标悬浮显示的时间

麻烦请说明一下这几个时间所在的具体位置 ~

**Comment by shichent** [comment]
> > 又发现几个比较隐蔽的北京时间还没有改过来：菠菜的用户投注时间，种子完成详情的完成时间和最近活动时间处鼠标悬浮显示的时间
> 
> 麻烦请说明一下这几个时间所在的具体位置 ~

https://kp.m-team.cc/bet_gameinfo?gameId=14271
这里下面用户投注的时间


https://kp.m-team.cc/complete/793131
这里，鼠标悬浮在每个用户完成时间和最近活动时间上时显示的时间

**Comment by shichent** [comment]
再补充一个，应求种子的发布时间[https://kp.m-team.cc/seekDetail?id=25543]()

还有，排行（旧版）里上传下载速度出现了负数，猜测是用了北京时间的注册时间，又用了本地时间作为当前时间：[https://kp.m-team.cc/top](url)

还还有，邀请系统页面下的邀请发送时间以及过期时间：[https://kp.m-team.cc/invite](url)

**Comment by jstvn** [comment]
> > > 又发现几个比较隐蔽的北京时间还没有改过来：菠菜的用户投注时间，种子完成详情的完成时间和最近活动时间处鼠标悬浮显示的时间
> > 
> > 
> > 麻烦请说明一下这几个时间所在的具体位置 ~
> 
> https://kp.m-team.cc/bet_gameinfo?gameId=14271 这里下面用户投注的时间
> 
> https://kp.m-team.cc/complete/793131 这里，鼠标悬浮在每个用户完成时间和最近活动时间上时显示的时间

done



> 再补充一个，应求种子的发布时间https://kp.m-team.cc/seekDetail?id=25543
> 
> 还有，排行（旧版）里上传下载速度出现了负数，猜测是用了北京时间的注册时间，又用了本地时间作为当前时间：[https://kp.m-team.cc/top](url)
> 
> 还还有，邀请系统页面下的邀请发送时间以及过期时间：[https://kp.m-team.cc/invite](url)

done
