### ISSUE TITLE
欧洲杯开始了，建议把发种页面的运动/体育类别挪到影视区，方便新人转发

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#302]
刚才发了个比赛视频，找半天没找到体育标签，结果发现体育标签跑到发种页面其他类别里面了，体育类基本上都是比赛视频，在大部分站点跟动漫、纪录片同属于影视类别，也希望能在馒头综合页面置顶帖看见欧洲杯体育赛事的视频，让大家知道馒头的体育比赛视频是永久免费的，可以用RSS订阅永久免费下载。

**Comment by mteamwhy** [comment]
如果要歸類到影視類,當初就不會獨立一個體育分類
