### ISSUE TITLE
快速審核候選回復

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#304]
於該欄增加審核回復
![image](https://github.com/mteamwhy/mt-web-pre/assets/30530524/9b140ba1-1b71-48c6-8d26-c38d32e886b3)

權限綁定候選管理以上

點擊後出現數個選項提供勾選，然後生成回復意見至回復框
以下為文案示意
選項新增在管理面板，方便隨時修改新增選項

主標題不正確的命名(包括但不限於有中文或特殊符號或命名錯誤)
資源分類選擇錯誤
來源/解析度/視頻編碼/音頻編碼錯誤
未填寫imdb/douban連結
未正確勾選中字或國配
mediainfo錯誤無法解析
bdinfo錯誤無法解析
簡介無法說明資源內容
轉載來源未正確說明
未附上三張以上影片實際截圖

文尾附上
修改完成後請利用種子舉報功能回報修改完成

**Comment by jstvn** [comment]
> 選項新增在管理面板，方便隨時修改新增選項

@jianglin8-hub 请安排一下相应的接口 ~

**Comment by jianglin8-hub** [comment]
setting 接口 TORRENT_FAST_COMMENT 字段，分隔符建议 “|||”

读取接口 /getConf
