### ISSUE TITLE
馒头的等级晋升没有考察做种积分，只强调刷流

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#305]
馒头用的还是十几年前Nexusphp的晋升方案，现在很多站点的等级晋升已经弱化刷流，要求达到相对的做种积分才能晋级，下面是时魔上限一百的站点的做种积分晋升要求，可以参考修改，不然有些人拆包下载9kg去普通影视区都是下完就跑，另外建议废除电子书战士这种速通积分的模式，反正PTPP现在已经不能下载馒头整页电子书，就不要搞这种时魔无上限的速通方案了，可以适当调高允许同时做种的统计个数。
![QQ图片20240630022152](https://github.com/mteamwhy/mt-web-pre/assets/103364093/efb741de-af2d-4a20-b57f-c850028501be)
![QQ图片20240630022205](https://github.com/mteamwhy/mt-web-pre/assets/103364093/80e24cfb-9414-4975-ae2e-51d3e57373ce)

**Comment by mteamwhy** [comment]
謝謝你的建議
