### ISSUE TITLE
官種魔力調整

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#306]
每個種子給予0.1%
每GB給予0.01%

不用等待24小時

**Comment by i990049** [comment]
建议官种改成永久免费+弹性HR，就算文件断种了，也不会因为下不完而占用用户的下载数据。别的全站HR的内站基本上被人诟病的就是下载大包不免费和断种照样计算HR，这方面还是参考外站，你要求用户HR，就不要计算用户的分享率和完成百分比，在外站就算PT软件用RSS自动下载了不免费的HR种子，搞个限速1KB下载也能拖够时间完成HR。
HR时间自动跟文件大小成为正比，以25GB为梯度，文件每增加25GB HR增多1天，要求HR的7倍时间内完成HR。可能没玩过HR的人觉得HR很不合理，那就大大方方告诉他，隔壁ADC要求文件每增加25GB HR增多1周，我们这里只要求1天，在国内目前的网络环境已经非常仁慈。
比如100G的文件，要求HR 4天，要求28天内完成HR。
1000G的文件，要求HR 40天，要求280天内完成HR。
40天虽然看起来很吓人，其实从下载到10%的时候就开始计算HR了，这样做也是为了防止发太大的文件包不能出种。
这样算下来，小过25GB的文件只要求HR 1天，要求7天内完成，平均下来每天也只要求做种3个多小时，越大的文件要求HR时间越久，就算断种也能完成HR，盒子可以刷流，但不能刷完就跑，家宽笔记本都能做种，每天只玩三个多小时也不会被运营商查水表。

**Comment by mteamwhy** [comment]
> 建议官种改成永久免费+弹性HR，就算文件断种了，也不会因为下不完而占用用户的下载数据。别的全站HR的内站基本上被人诟病的就是下载大包不免费和断种照样计算HR，这方面还是参考外站，你要求用户HR，就不要计算用户的分享率和完成百分比，在外站就算PT软件用RSS自动下载了不免费的HR种子，搞个限速1KB下载也能拖够时间完成HR。
> 
> HR时间自动跟文件大小成为正比，以25GB为梯度，文件每增加25GB HR增多1天，要求HR的7倍时间内完成HR。可能没玩过HR的人觉得HR很不合理，那就大大方方告诉他，隔壁ADC要求文件每增加25GB HR增多1周，我们这里只要求1天，在国内目前的网络环境已经非常仁慈。
> 
> 比如100G的文件，要求HR 4天，要求28天内完成HR。
> 
> 1000G的文件，要求HR 40天，要求280天内完成HR。
> 
> 40天虽然看起来很吓人，其实从下载到10%的时候就开始计算HR了，这样做也是为了防止发太大的文件包不能出种。
> 
> 这样算下来，小过25GB的文件只要求HR 1天，要求7天内完成，平均下来每天也只要求做种3个多小时，越大的文件要求HR时间越久，就算断种也能完成HR，盒子可以刷流，但不能刷完就跑，家宽笔记本都能做种，每天只玩三个多小时也不会被运营商查水表。

分享率站點不會考慮HR,謝謝你的建議

**Comment by i990049** [comment]
TL FL IPT这些也是有9kg的站点，人家既考核分享率也考核HR，馒头有些影视剧出来还不到一周就没几个人做种了，如果实在不想上HR，那把做种积分写进等级要求里面，这样也可以增加保种率
https://github.com/mteamwhy/mt-web-pre/issues/305#issuecomment-2199542919

**Comment by mteamwhy** [comment]
> 每個種子給予0.1%
> 
> 每GB給予0.01%
> 
> 
> 
> 不用等待24小時

在處理的同時請將連續做種的最小單位從5MB提升至10MB

**Comment by i990049** [comment]
> > 每個種子給予0.1%
> > 每GB給予0.01%
> > 不用等待24小時
> 
> 在處理的同時請將連續做種的最小單位從5MB提升至10MB

可以说大部分电子书战士都是冲着魔力去的，不会有几个人看完几千歌电子书，单位大小要求根本不是重点，目前晋级也跟做种积分无关，还不如改成任何普通种子都可以享受一楼的魔力加成，然后官种享受两倍加成，这样普通种子才会有人保种。

**Comment by i990049** [comment]
https://kp.m-team.cc/complete/797968
刚出的种子，几十个人下载，大部分下完就跑，只剩几个人做种，看来很多人买个盒子速通一下上传就不需要保种

**Comment by jianglin8-hub** [comment]
已上线 @mteamwhy
