### ISSUE TITLE
發佈頁面標記更改

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#308]
![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/08f6565a-73f0-482e-93fa-521765feb673)

取消diy、國配選項
增加
4k = width 3840 / bdinfo偵測Ultra HD
8k = width 7680
hdr
hdr10
hdr10+
hlg
Dolby Vision(DoVi)
HDR Vivid(HDRVi)

以上選項不開放會員選取，發佈頁不顯示，自動分析mediainfo後顯示
中字選項保留給會員選取

種子列表比照以往
種子詳情頁於mediainfo下方增加標記欄顯示

**Comment by mteamwhy** [comment]
> ![圖片](https://private-user-images.githubusercontent.com/30530524/345314958-08f6565a-73f0-482e-93fa-521765feb673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTM2NDAsIm5iZiI6MTcxOTk5MzM0MCwicGF0aCI6Ii8zMDUzMDUyNC8zNDUzMTQ5NTgtMDhmNjU2NWEtNzNmMC00ODJlLTkzZmEtNTIxNzY1ZmViNjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3NTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2FlODBhZmIyMjgxYzhiMjIzODAxMGM3MDhmODU4Y2Q2MTUyYjg4ZWIwYjhlYzZmMDg3OTYzZmQwMmI4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bS82OFbAraxRxc9S7cX6ocVzyMyXGxYx829PEsbNwxc)
> 
> 取消diy、國配選項 增加 4k = width 3840 / bdinfo偵測Ultra HD 8k = width 7680 hdr hdr10 hdr10+ hlg Dolby Vision(DoVi) HDR Vivid(HDRVi)
> 
> 以上選項不開放會員選取，發佈頁不顯示，自動分析mediainfo後顯示 中字選項保留給會員選取
> 
> 種子列表比照以往 種子詳情頁於mediainfo下方增加標記欄顯示

@jianglin8-hub

完成後請重新跑一遍mediainfo解析幫助舊有資源標記

**Comment by i990049** [comment]
什么时候可以像unit3d那样可以搜索默认音轨是哪国语言？

**Comment by mteamwhy** [comment]
> 什么时候可以像unit3d那样可以搜索默认音轨是哪国语言？

需求請另開討論
然而有大量他站資源音軌不帶語言或是錯誤

**Comment by jianglin8-hub** [comment]
```
种子列表、详情、搜索、发布、编辑 已增加  labelsNew 字段（String数组）

系统设置字段：TORRENT_LABLE_CONFIG ，以下是格式，JSON String
[
    {
        "tag": "中字",
        "color": "#fff",
        "bgColor": ""
    },
    {
        "tag": "国配",
        "color": "#fff",
        "bgColor": ""
    }
]

```
@freedomlang 有空看下

原 labels 字段延后转换。

**Comment by i990049** [comment]
> ```
> 种子列表、详情、搜索、发布、编辑 已增加  labelsNew 字段（String数组）
> 
> 系统设置字段：TORRENT_LABLE_CONFIG ，以下是格式，JSON String
> [
>     {
>         "tag": "中字",
>         "color": "#fff",
>         "bgColor": ""
>     },
>     {
>         "tag": "国配",
>         "color": "#fff",
>         "bgColor": ""
>     }
> ]
> ```
> 
> @freedomlang 有空看下
> 
> 原 labels 字段延后转换。

还有粤语配音，台剧还有闽南语配音

**Comment by i990049** [comment]
https://github.com/mteamwhy/mt-web-pre/issues/310
既然添加了标签，建议搜索箱里面也提供搜索国粤台音轨

**Comment by mteamwhy** [comment]
> #310 既然添加了标签，建议搜索箱里面也提供搜索国粤台音轨

需求請另開issue

**Comment by mteamwhy** [comment]
> ```
> 种子列表、详情、搜索、发布、编辑 已增加  labelsNew 字段（String数组）
> 
> 系统设置字段：TORRENT_LABLE_CONFIG ，以下是格式，JSON String
> [
>     {
>         "tag": "中字",
>         "color": "#fff",
>         "bgColor": ""
>     },
>     {
>         "tag": "国配",
>         "color": "#fff",
>         "bgColor": ""
>     }
> ]
> ```
> 
> @freedomlang 有空看下
> 
> 原 labels 字段延后转换。

國配取消

**Comment by jianglin8-hub** [comment]
> > ```
> > 种子列表、详情、搜索、发布、编辑 已增加  labelsNew 字段（String数组）
> > 
> > 系统设置字段：TORRENT_LABLE_CONFIG ，以下是格式，JSON String
> > [
> >     {
> >         "tag": "中字",
> >         "color": "#fff",
> >         "bgColor": ""
> >     },
> >     {
> >         "tag": "国配",
> >         "color": "#fff",
> >         "bgColor": ""
> >     }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @freedomlang 有空看下
> > 原 labels 字段延后转换。
> 
> 國配取消

这是样例，没实际配置
