### ISSUE TITLE
进入部分种子界面时会跳出如下代码

### ISSUE THREAD

**Issue by sanqianxingluo** [mteamwhy/mt-web-pre#311]
Unexpected Application Error! Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings. Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings. at hi (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:1992743) at f (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:1994511) at m (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:1995658) at e (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:1997719) at mc (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2015838) at bl (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2064764) at hs (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2052043) at fs (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2051971) at ds (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2051834) at es (https://static.m-team.cc/static/js/vendors.1302f4ba.js:2:2048614)

**Comment by wzyq1996** [comment]
遇到了同样的问题，在访问https://kp.m-team.cc/detail/484634 后遇到报错
![Snipaste_2024-07-07_01-25-30](https://github.com/mteamwhy/mt-web-pre/assets/174948077/9263257a-a77f-4067-93e6-73ce4589df29)

**Comment by jianglin8-hub** [comment]
fixed
