### ISSUE TITLE
种子不能下载。种子提示 状态：未工作。 消息：向一个无法连接的网络尝试了一个套接字操作。

### ISSUE THREAD

**Issue by xiaoalbee** [mteamwhy/mt-web-pre#313]
站點用戶名稱:
xiaoalbee
所在省份及運營商:
四川成都，中国移动
站點錯誤訊息:
MT
![Uploading 7502df380ac08aaa93ddd131d36699b3.png…]()
之前都正常的，突然就不行，种子提示 状态：未工作。 消息：向一个无法连接的网络尝试了一个套接字操作。
补充內容:
原来已下载好的种子，和现在新下的。 Tracker都提示：状态：未工作。 消息：向一个无法连接的网络尝试了一个套接字操作。用下载工具用的是QB 4.5 ，Win7系统。软件重启，电脑重启，都不行。其他PT站下载正常。

**Comment by xiaoalbee** [comment]
![7502df380ac08aaa93ddd131d36699b3](https://github.com/mteamwhy/mt-web-pre/assets/174943943/2faa16fe-4246-43e2-b1d2-9424178c7ce3)
![f255c66cc86e09395cb7a6fb315452dc](https://github.com/mteamwhy/mt-web-pre/assets/174943943/50cfdddf-ed11-4c81-a2d0-6bbd38b9ad5b)
![83b46f2e8b019fadcb4ba20e6b36f4e3](https://github.com/mteamwhy/mt-web-pre/assets/174943943/31a365bc-3931-4227-a8a9-ffed3d507322)
![4d6b3d810c6165be935a1421ab350c49](https://github.com/mteamwhy/mt-web-pre/assets/174943943/fe08749d-dc54-494a-ba45-738893927141)

**Comment by jianglin8-hub** [comment]
手动在浏览器访问 https://tracker.m-team.cc/ ，显示的是什么？

**Comment by mteamwhy** [comment]
先換網址吧,應該是sni阻斷

**Comment by xiaoalbee** [comment]
手动浏览器输入，显示这个。不能打开这个网址。在 2024年7月10日，13:51，jianglin8 ***@***.***> 写道：﻿
手动在浏览器访问 https://tracker.m-team.cc/ ，显示的是什么？

**Comment by xiaoalbee** [comment]
怎么换网址呢？我需要如何操作。在 2024年7月10日，16:44，mteamwhy ***@***.***> 写道：﻿
先換網址吧,應該是sni阻斷

**Comment by jianglin8-hub** [comment]
把cc 域名换成 io

**Comment by xiaoalbee** [comment]
> 把 cc 域名换成 io

不行，还是打不开。

**Comment by xiaoalbee** [comment]
> 首先换网址吧，该死的

换哪个网址？

**Comment by xiaoalbee** [comment]
> 手动在浏览器访问https://tracker.m-team.cc/，显示的是什么？

打不开 后面cc换成io还是打不开。

**Comment by jianglin8-hub** [comment]
网络环境有梯子？
或者梯子的规则配置错误导致的？

**Comment by jianglin8-hub** [comment]
ping tracker.m-team.cc
解析的IP是什么

**Comment by xiaoalbee** [comment]
> 网络环境有梯子吗？ 或者梯子的规则配置错误导致的？

我苹果ATV用了梯子 网络 。会不会是这个原因呢？但是没看ATV 我就把梯子(小火箭）关了的。

**Comment by mteamwhy** [comment]
> > 手动在浏览器访问https://tracker.m-team.cc/，显示的是什么？
> 
> 
> 
> 打不开 后面cc换成io还是打不开。

控制台有四個,都試試

**Comment by mteamwhy** [comment]
上tg問吧

**Comment by xiaoalbee** [comment]
> ping tracker.m-team.cc 解析的IP是什么

![Uploading IMG_2678.jpeg…]()

**Comment by xiaoalbee** [comment]
![IMG_2678](https://github.com/mteamwhy/mt-web-pre/assets/174943943/d264ab80-0f2c-41be-96f0-ae842732a437)

**Comment by jianglin8-hub** [comment]
> ![IMG_2678](https://private-user-images.githubusercontent.com/174943943/347340150-d264ab80-0f2c-41be-96f0-ae842732a437.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDMzNzgsIm5iZiI6MTcyMDYwMzA3OCwicGF0aCI6Ii8xNzQ5NDM5NDMvMzQ3MzQwMTUwLWQyNjRhYjgwLTBmMmMtNDFiZS05NmYwLWFlODQyNzMyYTQzNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDkxNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQwZTFiMTA2MTBlMmVjMTIyNWNhNGIzNmJjMjkxNjZhZDQ0MzEyNmM2MjAxZDlmNTBhNDM3M2UyZTU2ZDMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BM4DYvbEl1Pp5svj5tYp7PpfhqUGuXPG6MqBn2SLa6E)

解析的IP看起来没问题，不知道是不是win7的缘故，你可以连wifi在手机上尝试访问。
