### ISSUE TITLE
适配跨平台客户端

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#315]
freedownloadmanager v6.24
https://www.freedownloadmanager.org/download.htm
Client Agent
FDM/6.24.0.5818
peer id=FD6(jMAV

FrostWire v6.13.2 build 321
https://www.frostwire.com/downloads
Client Agent
FrostWire/6.13.2 libtorrent/1.2.19.0
peer_id=-FW6D21-

顺便问问贵站不允许Bitcomet和Webtorrent Desktop的理由是什么？这些都是跨平台的软件，谢谢

**Comment by mteamwhy** [comment]
~1.不支持任何邊下載邊播放的軟體~
2.不支持跨協議下載功能的軟體

**Comment by i990049** [comment]
> 1.不支持任何邊下載邊播放的軟體 2.不支持跨協議下載功能的軟體

那utorrent、Azureus和Bigly BT也能调用播放器边下边播，为什么贵站又支持呢？

**Comment by mteamwhy** [comment]
> > 1.不支持任何邊下載邊播放的軟體 2.不支持跨協議下載功能的軟體
> 
> 那utorrent、Azureus和Bigly BT也能调用播放器边下边播，为什么贵站又支持呢？

我說的不嚴謹是我的錯，
不支持跨協議是主要原因，且由於我們技術力並不足於判斷該軟體是否適用於pt，請多見諒

**Comment by i990049** [comment]
> > > 1.不支持任何邊下載邊播放的軟體 2.不支持跨協議下載功能的軟體
> > 
> > 
> > 那utorrent、Azureus和Bigly BT也能调用播放器边下边播，为什么贵站又支持呢？
> 
> 我說的不嚴謹是我的錯， 不支持跨協議是主要原因，且由於我們技術力並不足於判斷該軟體是否適用於pt，請多見諒

其实这篇文章里面说到的全部软件在unit3d上面使用，都没有什么问题，十几年前的bitspirit也能边下边播，frostwire跟bitlord一样只是把播放器整合到软件里面，bitcomet跟freedownmanager一样是支持多协议下载，多协议不是跨协议，真正的跨协议是十几年前一个叫脱兔的软件，同一个文件可以同时给BT和ed传输。其实Azureus和Bigly BT跟webtorrent desktop一样支持webrtc协议，贵站允许前两者使用那么久，有引起过问题吗？后者还是watchsomuch默认推荐的软件，建议站长有空去unit3d站点试用一下本文这些软件，随便下载几个热门种子就知道有没有问题了。如果不行，那就不勉强了，谢谢。
