### ISSUE TITLE
菠菜重复投注bug

### ISSUE THREAD

**Issue by shichent** [mteamwhy/mt-web-pre#316]
参考：[https://kp.m-team.cc/forum/t/5481?page=22#p303196](https://kp.m-team.cc/forum/t/5481?page=22#p303196)

菠菜不允许重复投注，但是如果重复投注的话，魔力值会减少，积分记录会显示变化原因为菠菜投注。经过测试，已经封盘或者结算的菠菜，如果通过api下注，魔力也会减少，积分记录也有显示。请修复。

**Comment by mteamwhy** [comment]
fix
