### ISSUE TITLE
qb RSS无法订阅

### ISSUE THREAD

**Issue by AguaC1** [mteamwhy/mt-web-pre#320]
nas使用qb订阅RSS 原本正常 在最近无法刷新rss订阅信息 订阅失效
![QB](https://github.com/user-attachments/assets/a589c3a3-0611-422e-b2b5-24d2e54ff3d1)

**Comment by jianglin8-hub** [comment]
贴到浏览器打开试试

**Comment by AguaC1** [comment]
浏览器打开正常
但是在QB无法刷新

**Comment by AguaC1** [comment]
> 贴到浏览器打开试试

浏览器打开正常
但是在QB无法刷新

**Comment by AguaC1** [comment]
> 贴到浏览器打开试试

![image](https://github.com/user-attachments/assets/a7d27ffe-253d-4434-baf9-e1efd549376b)

**Comment by jianglin8-hub** [comment]
图片删除或打码。

重启 或 更新客户端版本呢？

**Comment by AguaC1** [comment]
> 图片删除或打码。
> 
> 重启 或 更新客户端版本呢？

重启没用 版本的话应该是最新版本
![image](https://github.com/user-attachments/assets/fbb3591e-3ff7-4f68-90bf-44fa266d3b6e)

**Comment by jianglin8-hub** [comment]
设置-高级

https证书验证
SSRF缓解

的选项调整试试，另外看看qb有没有日志

**Comment by DaPoHou** [comment]
有可能也是被cloudflare waf阻断了。
群晖无法rss订阅下载种子问题也是因为这个。
