### ISSUE TITLE
无法下载种子是cloudflare的问题，希望关闭waf

### ISSUE THREAD

**Issue by DaPoHou** [mteamwhy/mt-web-pre#322]
通过仔细排查，发现群晖无法通过RSS订阅下载是被CloudFlare所阻挡了。 群晖通过RSS订阅获取到的种子链接是类似于api.m-team.cc/api/rss/dlv2动态链接，然后通过302跳转到网站个人设定的“下載種子域名”上。 因为“下載種子域名”外层套了CloudFlare并开启了waf，导致被CloudFlare WAF拦截无法下载到正确的种子文件（包括其他人反映的qb无法通过rsd下载种子应该都是这个原因）。

个人认为： 既然种子下载链接api.m-team.cc/api/rss/dlv2中的sign=已经是动态生成的了，就没必要再在“下載種子域名”外层的CloudFlare上开启WAF规则。除了通过浏览器下载，其他方式cloudflare waf均有可能会出现误判拦截。

希望官方能关闭“下載種子域名”列表中所有或部分域名的CloudFlare WAF规则，以便有问题的用户选择使用，感谢！！

**Comment by mteamwhy** [comment]
群暉的什麼?
downloadstation??

**Comment by DaPoHou** [comment]
> 群暉的什麼? downloadstation??

是的。无法通过rss订阅下载种子文件。都是在302跳转到“下载种子域名”后被cf的waf阻拦了。
个人认为对这些域名开启waf必要性不大，应尽可能的兼容各种客户端保证能正常下载才对。

**Comment by mteamwhy** [comment]
不支持DS

**Comment by DaPoHou** [comment]
> 不支持DS

不支持DS的原因就是因为CloudFlare的waf问题，导致无法正常下载到种子文件。
如果关闭cloudflare的waf，DS应该就能正常使用了。
https://github.com/mteamwhy/mt-web-pre/issues/114 这里提到的错误就是waf的问题。
包括https://github.com/mteamwhy/mt-web-pre/issues/320 这里面提到的，应该也是waf的问题。

**Comment by mteamwhy** [comment]
> > 不支持DS
> 
> 
> 
> 不支持DS的原因就是因为CloudFlare的waf问题，导致无法正常下载到种子文件。
> 
> 如果关闭cloudflare的waf，DS应该就能正常使用了。
> 
> https://github.com/mteamwhy/mt-web-pre/issues/114 这里提到的错误就是waf的问题。
> 
> 包括https://github.com/mteamwhy/mt-web-pre/issues/320 这里面提到的，应该也是waf的问题。

兩者無關連,麻煩給一下被cf攔截的畫面截圖

**Comment by DaPoHou** [comment]
> 兩者無關連,麻煩給一下被cf攔截的畫面截圖

之前我請求群暉官方人員支援，得到的反饋是如此。群暉DS使用curl下載種子，被cloudflare阻攔了。

其實測試方法很簡單，可以在cloudflare —— WAF、自動程序和安全設定裏面，暫時關閉一個下載種子域名的所有安全防護
(1. WAF中添加自定義規則，黨請求方法為GET，跳過所有規則；
2. 關閉自動程序所有選項
3. 安全設定選擇“基本關閉 Essentially off”，並關閉下方的的浏览器完整性检查 )。

然後我這邊使用DS看是否可以正常下載種子即可。

**Comment by mteamwhy** [comment]
> > 兩者無關連,麻煩給一下被cf攔截的畫面截圖
> 
> 
> 
> 之前我請求群暉官方人員支援，得到的反饋是如此。群暉DS使用curl下載種子，被cloudflare阻攔了。
> 
> 
> 
> 其實測試方法很簡單，可以在cloudflare —— WAF、自動程序和安全設定裏面，暫時關閉一個下載種子域名的所有安全防護
> 
> (1. WAF中添加自定義規則，黨請求方法為GET，跳過所有規則；
> 
> 2. 關閉自動程序所有選項
> 
> 3. 安全設定選擇“基本關閉 Essentially off”，並關閉下方的的浏览器完整性检查 )。
> 
> 
> 
> 然後我這邊使用DS看是否可以正常下載種子即可。

已經說過沒有關連了,別的qb都是正常運作

**Comment by capesl** [comment]
遇到同样问题。
就不能关闭了测试一下？
