### ISSUE TITLE
scrape的响应不对

### ISSUE THREAD

**Issue by trim21** [mteamwhy/mt-web-pre#323]
针对 d011d55c8138bce55556d61bf988e6088865e7d4 的 scrape 响应现在是这样的：

（https://tracker.m-team.cc/scrape.php?passkey=...&info_hash=%D0%11%D5%5C%818%BC%E5UV%D6%1B%F9%88%E6%08%88e%E7%D4）

```python
d5:filesd32:\xc3\x90\x11\xc3\x95\\\xc2\x818\xc2\xbc\xc3\xa5UV\xc3\x96\x1b\xc3\xb9\xc2\x88\xc3\xa6\x08\xc2\x88e\xc3\xa7\xc3\x94d8:completei58e10:downloadedi0e10:incompletei3eeee
```

不知道java里面怎么表示原始二进制数据，base64之后是这样的：`ZDU6ZmlsZXNkMzI6w5ARw5VcwoE4wrzDpVVWw5Ybw7nCiMOmCMKIZcOnw5RkODpjb21wbGV0ZWk1OGUxMDpkb3dubG9hZGVkaTBlMTA6aW5jb21wbGV0ZWkzZWVlZQ==`

```text
{
  'files': {
    bytes.fromhex('c39011c3955cc28138c2bcc3a55556c3961bc3b9c288c3a608c28865c3a7c394'): {'complete': 58, 'downloaded': 0, 'incomplete': 3},
  }
}
```

他应该是这样：

```
d5:filesd20:\xd0\x11\xd5\\\x818\xbc\xe5UV\xd6\x1b\xf9\x88\xe6\x08\x88e\xe7\xd4d8:completei58e10:downloadedi0e10:incompletei3eeee
```

(base64 `ZDU6ZmlsZXNkMjA60BHVXIE4vOVVVtYb+YjmCIhl59RkODpjb21wbGV0ZWk1OGUxMDpkb3dubG9hZGVkaTBlMTA6aW5jb21wbGV0ZWkzZWVlZQ==`)

```text
{
    b"files": {
        bytes.fromhex("d011d55c8138bce55556d61bf988e6088865e7d4"): {
            b"complete": 58,
            b"downloaded": 0,
            b"incomplete": 3,
        }
    }
}
```

这里 `files` 这个 bencode dict 的 key 应该是原始的 info_hash 原始二进制数据。长度应该是 20，而不是 32.

https://www.bittorrent.org/beps/bep_0048.html

现在QB可以正常识别响应，应该是做了兼容.

**Comment by jianglin8-hub** [comment]
处理了
