### ISSUE TITLE
求種區增加排序功能

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#329]
請將應求數量及評論數量加入排序，方便管理巡查

![image](https://github.com/user-attachments/assets/53ce4c53-80c7-4436-ae9e-6045c4b8b1f8)

**Comment by jianglin8-hub** [comment]
```
排序字段增加：

comments 评论数
submitNum 响应数
takeNum 采纳数
```

@freedomlang
