### ISSUE TITLE
隱私等級為高的顯示內容調整

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#330]
等級為高時，被查看時不顯示用戶名稱，顯示匿名
![image](https://github.com/user-attachments/assets/c3fc2c72-6a6e-4319-93ab-b1566613c969)

於種子評論的時候，顯示匿名

於論壇回帖的時候，顯示匿名

發佈趣味盒時，顯示匿名

**Comment by hahahaozi** [comment]
发布求种匿名

**Comment by mteamwhy** [comment]
> 发布求种匿名

求種區的發佈及評論皆匿名

**Comment by mteamwhy** [comment]
波菜結算頁的用戶名稱改為uid顯示

**Comment by ixff** [comment]
> > 发布求种匿名
> 
> 求種區的發佈及評論皆匿名

匿名应求者在求种帖下的评论能否匿名？

**Comment by jianglin8-hub** [comment]
测试环境已上（不含菠菜页改UID展示）

测试时请使用无权限账号

**Comment by mteamwhy** [comment]
> 测试环境已上（不含菠菜页改UID展示）
> 
> 测试时请使用无权限账号

直接查詢對應uid的網址還是有顯示用戶名稱

**Comment by jianglin8-hub** [comment]
> > 测试环境已上（不含菠菜页改UID展示）
> > 测试时请使用无权限账号
> 
> 直接查詢對應uid的網址還是有顯示用戶名稱

现在做法是：当用户隐私为“高”时，在评论列表中不返回用户ID（理论上来说，不知道UID的情况下是无法获取用户名的）
通过UID获取用户名仍是允许的

**Comment by mteamwhy** [comment]
> > > 测试环境已上（不含菠菜页改UID展示）
> 
> > > 测试时请使用无权限账号
> 
> > 
> 
> > 直接查詢對應uid的網址還是有顯示用戶名稱
> 
> 
> 
> 现在做法是：当用户隐私为“高”时，在评论列表中不返回用户ID（理论上来说，不知道UID的情况下是无法获取用户名的）
> 
> 通过UID获取用户名仍是允许的
> 
> 

問題中自購資源證明中
1.不願意寫username
2.寫uid又會被直接訪問得username

除非有好的辦法取代自購資源證明方式,不然還是得改

那只能變成所有證明都是工單申請了(至少不會被得知uid直接訪問)

**Comment by mteamwhy** [comment]
> > > > 测试环境已上（不含菠菜页改UID展示）
> > 
> > > > 测试时请使用无权限账号
> > 
> > > 
> > 
> > > 直接查詢對應uid的網址還是有顯示用戶名稱
> > 
> > 
> > 
> > 现在做法是：当用户隐私为“高”时，在评论列表中不返回用户ID（理论上来说，不知道UID的情况下是无法获取用户名的）
> > 
> > 通过UID获取用户名仍是允许的
> > 
> > 
> 
> 問題中自購資源證明中
> 1.不願意寫username
> 2.寫uid又會被直接訪問得username
> 
> 除非有好的辦法取代自購資源證明方式,不然還是得改

得讓管理組核對該資源是否真的為該用戶所有
