### ISSUE TITLE
种子详情编辑记录的显示格式

### ISSUE THREAD

**Issue by ixff** [mteamwhy/mt-web-pre#331]
edited

**Comment by jianglin8-hub** [comment]
无权限用户看不到是谁编辑的

**Comment by mteamwhy** [comment]
> > 无权限用户看不到是谁编辑的
> 
> 已经工单沟通过，管理让我来这发issue。但我不太清楚你们内部怎么沟通的。

麻煩提供種子id，這邊查詢是看不到的

**Comment by mteamwhy** [comment]
別人看不到編輯紀錄，樣式問題會找時間統一調整
