### ISSUE TITLE
API提供的資訊有誤

### ISSUE THREAD

**Issue by kojuro-date** [mteamwhy/mt-web-pre#333]
用API取得成人種子的列表，但是發現有幾個discount顯示錯誤 網頁面寫FREE 2天，但是API卻取得說是NORMAL的狀態 導致相關的PT助手有點錯亂，沒辦法自動下載免費的資源

簡單搜索一下發現id: 555833的種子也是有免費狀態，但是API卻是NORMAL的這樣

![image](https://github.com/user-attachments/assets/448cd680-8b04-464e-86ac-d2f3bcbc981a)

**Comment by jianglin8-hub** [comment]
除现有的discount字段，还需要判断mallSingleFree字段，free到期时间为endDate字段

**Comment by kojuro-date** [comment]
了解，我測試看看
