### ISSUE TITLE
关于“持續在線做種獎勵加成”的建议

### ISSUE THREAD

**Issue by BlackJones** [mteamwhy/mt-web-pre#334]
建议将持续做种时长超过24小时的种子ID与个人绑定，类似已购买一样。成为“个人资产”。
然后在机器/客户端重启时，当做种ID在“个人资产”里，即时获取奖励。

**Comment by i990049** [comment]
搞这个还不如搞HR或者等级晋升跟做种积分挂钩，不是每个人都用nas24小时开机

**Comment by BlackJones** [comment]
> 搞这个还不如搞HR或者等级晋升跟做种积分挂钩，不是每个人都用nas24小时开机

是啊，不是每个人都用nas24小时开机，所以很多人的持续做种奖励得不到。。

**Comment by mteamwhy** [comment]
> 建议将持续做种时长超过24小时的种子ID与个人绑定，类似已购买一样。成为“个人资产”。
> 
> 然后在机器/客户端重启时，当做种ID在“个人资产”里，即时获取奖励。

因為這個設計叫持續做種獎勵,非即時做種獎勵

即時做種獎勵請參考官種

**Comment by mteamwhy** [comment]
> 建议将持续做种时长超过24小时的种子ID与个人绑定，类似已购买一样。成为“个人资产”。
> 
> 然后在机器/客户端重启时，当做种ID在“个人资产”里，即时获取奖励。

因為這個設計叫持續做種獎勵,非即時做種獎勵

即時做種獎勵請參考官種
