### ISSUE TITLE
建议支持webp格式图片

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#335]
现在豆瓣和imdb有部分海报都是webp格式的，用ptgen发内容介绍的时候浏览器有缓存显示图片没问题，结果种子审核说图片不显示，闹了半天才知道站点不支持webp格式，现在国内就一个站点pttime支持上传webp格式图片，希望增加支持。

**Comment by mteamwhy** [comment]
站點支持也能夠上傳webp格式

看不到圖片是有些站是檔外鏈吧？

麻煩提供相關種子id來檢查

**Comment by jianglin8-hub** [comment]
webp格式需客户端(浏览器)支持，较老版本的客户端可能不支持这种图片格式。

你的问题可能是其它原因，douban提供的图片链接会限制第三方网站访问，导致其它人无法查看此图片，建议通过编辑器上传到本站图库

**Comment by BlueSkyClouds** [comment]
可能是跨域 F12看看
