### ISSUE TITLE
个人主页BT用户端无法显示ipv6地址

### ISSUE THREAD

**Issue by jerichon** [mteamwhy/mt-web-pre#341]
你好，NAS和iqb能正确获取ipv6地址，但是在主页的个人资料页面却不能显示，只显示N/A，在iqb端也能连接到ipv6用户

**Comment by mteamwhy** [comment]
id???

**Comment by jerichon** [comment]
> id???

你好，276945麻烦你看一下

**Comment by jianglin8-hub** [comment]
1. 检查做种机是否有v6 IP
2. 检查能否访问纯V6网站
3. 检查做种域名是否有v6 ip解析结果
