### ISSUE TITLE
发种页面成人有码分类dmm搜索框回车无反应

### ISSUE THREAD

**Issue by TnZzZHlp** [mteamwhy/mt-web-pre#342]
如下图所示，输入番号后按下键盘回车无任何响应，f12控制台没有任何报错。使用windows自带的虚拟键盘回车可以正常搜索
OS：Windows11 23H2
浏览器：Microsoft Edge 128.0.2739.79 (正式版本) (64 位)

![image](https://github.com/user-attachments/assets/e86acc20-cebc-4261-9dce-d51143e4a0a6)

**Comment by jianglin8-hub** [comment]
未复现

**Comment by TnZzZHlp** [comment]
抱歉没注意回复，复现视频如下
试了下小键盘的回车无反应，普通的回车键没问题

https://github.com/user-attachments/assets/b84b3c3c-e30e-404c-9816-35ceb2d91962

**Comment by jianglin8-hub** [comment]
@freedomlang 看一下噢

**Comment by jianglin8-hub** [comment]
已修复
