### ISSUE TITLE
站点生成的RSS 放到QB里面无法下载 提示加载 URL错误或者无法下

### ISSUE THREAD

**Issue by wiz199** [mteamwhy/mt-web-pre#343]
刚刚生成RSS是可以下载的 但是过一会就不行了
![55555555555555555555555555](https://github.com/user-attachments/assets/2351cee3-650e-4831-8768-9a3352c083b9)
![66666666](https://github.com/user-attachments/assets/1fd74a12-2448-4586-933b-6497dc8b6693)
![77777777777](https://github.com/user-attachments/assets/13731bdf-4a6b-4a5d-a8be-8d17c6c6b917)
![8888888888](https://github.com/user-attachments/assets/a1d9006a-b919-4bd4-bbd4-f6cb74983659)
![999999999999](https://github.com/user-attachments/assets/6c1c75bd-7d84-4667-a93c-c5b35176ed5e)

**Comment by jianglin8-hub** [comment]
通过站内手动获取 或 RSS链接获取的下载链接，均有时效限制，目前超过5分钟自动作废。

**Comment by wiz199** [comment]
> 过站内手动

那rss 就没办法在qb中订阅了?

**Comment by mteamwhy** [comment]
> > 过站内手动
> 
> 那rss 就没办法在qb中订阅了?

刪除rss重新拉取，或是利用收藏RSS功能，或是利用rss關鍵字功能

**Comment by wiz199** [comment]
> > > 过站内手动
> > 
> > 
> > 那rss 就没办法在qb中订阅了?
> 
> 刪除rss重新拉取，或是利用收藏RSS功能，或是利用rss關鍵字功能

但是五分钟后不是就会过期 这样就没办法追跟新了呀

**Comment by mteamwhy** [comment]
> 利用rss關鍵字功能
利用rss關鍵字功能自動訂閱下載

**Comment by wiz199** [comment]
> > 利用rss關鍵字功能
> > 利用rss關鍵字功能自動訂閱下載

![image](https://github.com/user-attachments/assets/49498000-36c7-4fa5-bbbe-f0f8791e8d1f)

没有找到关键字功能  请问该如何操作

**Comment by wiz199** [comment]
> > 利用rss關鍵字功能
> > 利用rss關鍵字功能自動訂閱下載

![11111111111111111111](https://github.com/user-attachments/assets/2c7554f4-c9ab-4715-9d19-09b1d98d2210)
请问该如何操作 我没有找到关键字功能

**Comment by mteamwhy** [comment]
> > > 利用rss關鍵字功能
> 
> > > 利用rss關鍵字功能自動訂閱下載
> 
> 
> 
> ![11111111111111111111](https://github.com/user-attachments/assets/2c7554f4-c9ab-4715-9d19-09b1d98d2210)
> 
> 请问该如何操作 我没有找到关键字功能

qb 打開rss訂閱有相關功能

**Comment by wiz199** [comment]
![222222222222222222222222](https://github.com/user-attachments/assets/10428a46-ec47-4c69-b36a-3f9baf3f3ef5)
QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的

**Comment by mteamwhy** [comment]
> ![222222222222222222222222](https://github.com/user-attachments/assets/10428a46-ec47-4c69-b36a-3f9baf3f3ef5)
> 
> QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的

qb rss的自動下載不需要等五分鐘

**Comment by wiz199** [comment]
> > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> 
> qb rss的自動下載不需要等五分鐘

我知道 那之后想要更新每次都要重新拉取rss呀？

**Comment by mteamwhy** [comment]
> > > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> 
> > > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> 
> > 
> 
> > qb rss的自動下載不需要等五分鐘
> 
> 
> 
> 我知道 那之后想要更新每次都要重新拉取rss呀？

不需要,五分鐘指的是種子連結rss,不是網站產生的rss,網站的是永久的,種子是五分鐘

**Comment by wiz199** [comment]
> > > > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> > 
> > 
> > > > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> > 
> > 
> > > 
> > 
> > 
> > > qb rss的自動下載不需要等五分鐘
> > 
> > 
> > 我知道 那之后想要更新每次都要重新拉取rss呀？
> 
> 不需要,五分鐘指的是種子連結rss,不是網站產生的rss,網站的是永久的,種子是五分鐘

不好意思 我想再跟您理一遍  
1 在馒头站内生成RSS连接 并复制连接
2 打开QB RSS 点击 新RSS订阅 将馒头RSS黏贴
3 获取RSS的种子 
到此一切都正常 可以手动下载 RSS下载器也可以正常下载 
五分钟后 rss获取到的种子都无法下载 提示 加载RUL失败  QB的RSS 下载器就算识别到了关键字也无法下载，此时只能重新拉取馒头的RSS 才可以下载 但是五分钟后又不行了， 就想问可否解决这个问题

**Comment by mteamwhy** [comment]
> > > > > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> 
> > > 
> 
> > > 
> 
> > > > > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > qb rss的自動下載不需要等五分鐘
> 
> > > 
> 
> > > 
> 
> > > 我知道 那之后想要更新每次都要重新拉取rss呀？
> 
> > 
> 
> > 不需要,五分鐘指的是種子連結rss,不是網站產生的rss,網站的是永久的,種子是五分鐘
> 
> 
> 
> 不好意思 我想再跟您理一遍  
> 
> 1 在馒头站内生成RSS连接 并复制连接
> 
> 2 打开QB RSS 点击 新RSS订阅 将馒头RSS黏贴
> 
> 3 获取RSS的种子 
> 
> 到此一切都正常 可以手动下载 RSS下载器也可以正常下载 
> 
> 五分钟后 rss获取到的种子都无法下载 提示 加载RUL失败  QB的RSS 下载器就算识别到了关键字也无法下载，此时只能重新拉取馒头的RSS 才可以下载 但是五分钟后又不行了， 就想问可否解决这个问题

所以你的使用場景是什麼,拉取rss不自動下載,等你有空再按下載?

**Comment by mteamwhy** [comment]
qbb rss的關鍵字觸發也不用五分鐘呀?

**Comment by BlueSkyClouds** [comment]
只需要在下载前再拉取一次RSS数据即可，RSS返回的下载链接 有限期为5分钟

**Comment by wiz199** [comment]
> > > > > > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > qb rss的自動下載不需要等五分鐘
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我知道 那之后想要更新每次都要重新拉取rss呀？
> > 
> > 
> > > 
> > 
> > 
> > > 不需要,五分鐘指的是種子連結rss,不是網站產生的rss,網站的是永久的,種子是五分鐘
> > 
> > 
> > 不好意思 我想再跟您理一遍
> > 1 在馒头站内生成RSS连接 并复制连接
> > 2 打开QB RSS 点击 新RSS订阅 将馒头RSS黏贴
> > 3 获取RSS的种子
> > 到此一切都正常 可以手动下载 RSS下载器也可以正常下载
> > 五分钟后 rss获取到的种子都无法下载 提示 加载RUL失败  QB的RSS 下载器就算识别到了关键字也无法下载，此时只能重新拉取馒头的RSS 才可以下载 但是五分钟后又不行了， 就想问可否解决这个问题
> 
> 所以你的使用場景是什麼,拉取rss不自動下載,等你有空再按下載?

就是想让QB挂那边一有更新自动下载 像 比如 蜜柑计划 动漫花园的rss就可以  一有更新QB就自动下载 不需要手动再操作

**Comment by i990049** [comment]
馒头现在的种子不是passkey模式，RSS链接必须在更新后五分钟内马上下载，超时自行用种子下载

**Comment by mteamwhy** [comment]
> > > > > > > ![222222222222222222222222](https://private-user-images.githubusercontent.com/139467034/369388009-10428a46-ec47-4c69-b36a-3f9baf3f3ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDc5MDMsIm5iZiI6MTcyNjkwNzYwMywicGF0aCI6Ii8xMzk0NjcwMzQvMzY5Mzg4MDA5LTEwNDI4YTQ2LWVjNDctNGM2OS1iMzZhLTNmOWJhZjNmM2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwODMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTI2Mjc2OTZjMjA3NDViMWE0YmE1NmQ4OWE0YjI0ZmU0NDA5NzA1MzM0MmFlMzAyYjNiZGRlOWZlOWYyNDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3TjaRcDf_rpXx930gGZc73qIuAWWBtqsbiJzBYojoAQ)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > QB rss的功能 我明白 站内生成的rss五分钟后就会过期 没办法下载的
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > qb rss的自動下載不需要等五分鐘
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 我知道 那之后想要更新每次都要重新拉取rss呀？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 不需要,五分鐘指的是種子連結rss,不是網站產生的rss,網站的是永久的,種子是五分鐘
> 
> > > 
> 
> > > 
> 
> > > 不好意思 我想再跟您理一遍
> 
> > > 1 在馒头站内生成RSS连接 并复制连接
> 
> > > 2 打开QB RSS 点击 新RSS订阅 将馒头RSS黏贴
> 
> > > 3 获取RSS的种子
> 
> > > 到此一切都正常 可以手动下载 RSS下载器也可以正常下载
> 
> > > 五分钟后 rss获取到的种子都无法下载 提示 加载RUL失败  QB的RSS 下载器就算识别到了关键字也无法下载，此时只能重新拉取馒头的RSS 才可以下载 但是五分钟后又不行了， 就想问可否解决这个问题
> 
> > 
> 
> > 所以你的使用場景是什麼,拉取rss不自動下載,等你有空再按下載?
> 
> 
> 
> 就是想让QB挂那边一有更新自动下载 像 比如 蜜柑计划 动漫花园的rss就可以  一有更新QB就自动下载 不需要手动再操作

所以說了,下載連結在處理不需要五分鐘,了解了嗎

**Comment by trim21** [comment]
> 只需要在下载前再拉取一次RSS数据即可，RSS返回的下载链接 有限期为5分钟

qb的种子链接一直是第一次拉取到某个种子时候的下载链接，后续rss内的种子链接更新后这个链接也不会随之更新。
虽然每次rss里面的种子链接都是有效的，但是这些新的url没有被qb保存下来。
