### ISSUE TITLE
为什么mediainfo的中文字幕会显示英国国旗？

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#345]
https://kp.m-team.cc/detail/830436
可以不要显示国旗标志，要显示国旗就不要显示错误

**Comment by mteamwhy** [comment]
因為顯示的是英文的國旗

**Comment by i990049** [comment]
同样都有中文字幕，为什么别的种子可以显示中国国旗一楼的链接不显示？
https://kp.m-team.cc/detail/830463

**Comment by i990049** [comment]
况且一楼的链接mediainfo还有中文和西班牙 葡萄牙 德语字幕，为什么只有英国国旗？
