### ISSUE TITLE
字幕文件下载不了

### ISSUE THREAD

**Issue by xyranger** [mteamwhy/mt-web-pre#35]
{"message":"內部錯誤","data":null,"code":"1"}

**Comment by mteamwhy** [comment]
請給出哪個連結

**Comment by xyranger** [comment]
> 請給出哪個連結

https://[kp.m-team.cc/api/subtitle/dl?id=55071](https://kp.m-team.cc/api/subtitle/dl?id=55071)

**Comment by xyranger** [comment]
https://[kp.m-team.cc/api/subtitle/dl?id=55236](https://kp.m-team.cc/api/subtitle/dl?id=55236)
https://[kp.m-team.cc/api/subtitle/dl?id=55168](https://kp.m-team.cc/api/subtitle/dl?id=55168)

**Comment by jianglin8-hub** [comment]
现在似乎都好了？
