### ISSUE TITLE
关于瀑布流的一些小建议

### ISSUE THREAD

**Issue by Zaki2380** [mteamwhy/mt-web-pre#354]
关于瀑布流这一块有几点我自己的想法

1.现在这个瀑布流看着非常乱，而且最近web组发剧集基本都是连着发，基本瀑布流里面就全被铺满这个剧了，想从瀑布流里找到自己感兴趣的剧很难。
2.瀑布流还有一部分根本就显示不出来图片。
3.其实我建议可以搞一个tab栏，搞一个类似tmdb、豆瓣、moviepilot的那种当前趋势、当下热播热映、排行榜什么的，点击海报之后可以搜索当前站内资源，感觉要比当下的瀑布流要好一点

仅仅是我个人的一些想法，祝M-Team越来越好 : )

**Comment by mteamwhy** [comment]
1.善用搜索
2.善用分類
3.實在不滿意有會員開發油猴腳本可以參考一下
4.排行榜會再下次ui更新後加入
