### ISSUE TITLE
下载完成的种子没有显示进度条和完成的标志

### ISSUE THREAD

**Issue by kuroyako** [mteamwhy/mt-web-pre#358]
![2](https://github.com/user-attachments/assets/3c4dfe87-3e25-4d96-ab8d-0a75468efc70)
![3](https://github.com/user-attachments/assets/8e0d51f2-8f8e-43ad-b81b-40653d933a3e)

种子太多，无法全部截图，只选取了其中几个截了图，种子下载完了，Tracker都在正常工作，但网页上没有显示进度条和完成的标志

**Comment by mteamwhy** [comment]
請清除網站資料緩存或至實驗室點選清取快取
