### ISSUE TITLE
“未完成种子”列表依然显示已被删除的种子

### ISSUE THREAD

**Issue by seidea** [mteamwhy/mt-web-pre#360]
种子在下载中途被删种，依然显示在“未完成种子”列表中。

![m-team_profile_detail](https://github.com/user-attachments/assets/ee3e2a56-227c-4879-b17f-fdab67c96d32)

**Comment by flowclouds** [comment]
![image](https://github.com/user-attachments/assets/fa3b0c48-fb43-4115-abcb-a241cac6d1d1)
我这里也是这样，麻烦处理下啊。。。。

**Comment by BlueSkyClouds** [comment]
等待清理沉余数据的时候一并处理
