### ISSUE TITLE
bot订阅展示一下详情吧

### ISSUE THREAD

**Issue by flowclouds** [mteamwhy/mt-web-pre#362]
![image](https://github.com/user-attachments/assets/2519f656-6eb5-46fe-9107-0a29b0a07eb1)
麻烦详细内容页展示一下啊~~~~通知都发了，详情也一并发一下啊，还有就是活动通知麻烦机器人也通知一下啊~~~

**Comment by jianglin8-hub** [comment]
提醒你该打开网站了，被动保号。

**Comment by flowclouds** [comment]
> 提醒你该打开网站了，被动保号。

即使提醒保号，也可以设置到某等级可以显示详情的机制。。。
