### ISSUE TITLE
适配新客户端

### ISSUE THREAD

**Issue by i990049** [mteamwhy/mt-web-pre#363]
馒头wiki支持rtorrent
https://wiki.m-team.cc/zh-tw/download-rules
馒头站点有部分外国用户，在外国rtorrent的用户数量是仅次于qbittorrent的客户端，都是盒子大军默认的客户端，前几年疫情都没动静，最近更新了，下面peer id的上一行就是user agent
https://github.com/rakshasa/rtorrent/releases
大部分使用旧版
rtorrent/0.9.8/0.13.8
peer id
-lt0D80-
最近更新
rtorrent/0.10.0/0.14.0
peer id
-lt0E00-

**Comment by jianglin8-hub** [comment]
done.
