### ISSUE TITLE
ip被禁止访问

### ISSUE THREAD

**Issue by madwind** [mteamwhy/mt-web-pre#369]
ip突然被禁止访问 想咨询一下是什么原因
根据工单要求在这里贴出情况

用户名: madwind
![Weixin Screenshot_20241209122625](https://github.com/user-attachments/assets/2ee44748-9ffa-4c5d-95e2-2a571dfdb501)

**Comment by jianglin8-hub** [comment]
提供具体IP

**Comment by madwind** [comment]
180.143.174.178

**Comment by madwind** [comment]
> 提供具体IP

----

**Comment by jianglin8-hub** [comment]
> > 提供具体IP
> 
> 180.143.174.178

api请求频率异常

**Comment by madwind** [comment]
> > > 提供具体IP
> > 
> > 
> > 180.143.174.178
> 
> api请求频率异常

请问是永久封禁吗 有可能解封吗

**Comment by jianglin8-hub** [comment]
> > > > 提供具体IP
> > > 
> > > 
> > > 180.143.174.178
> > 
> > 
> > api请求频率异常
> 
> 请问是永久封禁吗 有可能解封吗

目前是永久性封禁，可以解除1次   后续还有这种情况依然会禁用。

**Comment by madwind** [comment]
那么我应该是调用 /api/torrent/genDlToken 超出限制了吗 请问这个限制可以在哪里可以看到? 也麻烦解封一下

**Comment by jianglin8-hub** [comment]
> 那么我应该是调用 /api/torrent/genDlToken 超出限制了吗 请问这个限制可以在哪里可以看到? 也麻烦解封一下

时间太长对应的日志已经删除了，没有办法追溯

**Comment by madwind** [comment]
那现在应该如何申请解封呢 我还想知道api的请求频率限制可以在哪里看到

**Comment by jianglin8-hub** [comment]
> 那现在应该如何申请解封呢 我还想知道api的请求频率限制可以在哪里看到

目前已解除封禁。
这个问题与流控无关，应合理调用api。例如：重复、大量、有规律的下载种子（基于安全考虑可能封IP或禁用账户）

**Comment by madwind** [comment]
![Weixin Screenshot_20241215102757](https://github.com/user-attachments/assets/d42fe0e0-c8c7-4d39-a667-7cafa0151700)
昨天我就尝试了一下登录 提示是变了 显示了具体的ip 但是还是被禁用的状态 现在也是如此

**Comment by jianglin8-hub** [comment]
> 180.143.174.178

再试试

**Comment by madwind** [comment]
> > 180.143.174.178
> 
> 再试试

好了 感谢
