### ISSUE TITLE
关于候选区未填写tmdb/豆瓣连接情况下其他版本显示-1

### ISSUE THREAD

**Issue by hahahaozi** [mteamwhy/mt-web-pre#37]
![image](https://github.com/mteamwhy/mt-web-pre/assets/30067842/337b94e8-0416-46ce-be7d-899e8cd1037d)
如图所示，显示-1相关种子

**Comment by mteamwhy** [comment]
因為邏輯判斷就是用imdb來找其他相同imdb的種子

**Comment by hahahaozi** [comment]
> 因為邏輯判斷就是用imdb來找其他相同imdb的種子

emmmm……那显示-1也不对 吧？（或者是个ui美观问题？）
