### ISSUE TITLE
windows 11 arm64版本qbittorrent无法下载

### ISSUE THREAD

**Issue by lyl2dora** [mteamwhy/mt-web-pre#370]
操作系统为macos,由于装有vpn软件,不想qbittorrent流量经由vpn,所以在parallels desktop虚拟机内建立的windows 11 arm64系统安装qbittorrent,结果报错'unspecified system error',其他站点可以正常下载, 如将虚拟机系统换为ubuntu并安装qb可正常下载,但影响IO性能.
<img width="906" alt="1" src="https://github.com/user-attachments/assets/056d9868-2465-443f-8780-61bfb6a5697d" />

**Comment by mteamwhy** [comment]
這是你的網路問題

**Comment by mteamwhy** [comment]
麻煩更換客戶端或網址,這並非網站程序問題
本問題關閉
