### ISSUE TITLE
请求在TOTP界面添加文本样式的TOTP密钥

### ISSUE THREAD

**Issue by LxnChan** [mteamwhy/mt-web-pre#40]
![image](https://github.com/mteamwhy/mt-web-pre/assets/46388610/3fe36cd7-d12b-408e-8735-4abfefeb596a)

**请求在开启TOTP的界面添加文本样式的TOTP密钥，对于自建Vaultwarden这种没法扫码（没下载客户端）的有点难搞哦，谢谢啦。**

![image](https://github.com/mteamwhy/mt-web-pre/assets/46388610/8af1704f-bf48-4b4f-a3c1-4522b0c86451)

**Comment by jmdweem** [comment]
有一个临时的解决方法，就是用bitwarden的浏览器插件，可以直接扫描当前网页的二维码
![image](https://github.com/mteamwhy/mt-web-pre/assets/90380039/f3dd86e5-6a74-4f82-a9b3-a45826fa36fd)

**Comment by mteamwhy** [comment]
無此計劃
