### ISSUE TITLE
高级查询中勾选的分类在点击分页按钮后丢失

### ISSUE THREAD

**Issue by nanoia** [mteamwhy/mt-web-pre#41]
高级查询勾选分类后，点击查询，此时的 Query Payload: 
`{"mode":"adult","categories":["425","433"],"visible":1,"pageNumber":1,"pageSize":100}`

点击第2页后，高级查询中勾选的分类被取消，此时的 Query Payload: 
`{"mode":"adult","categories":[],"visible":1,"sortDirection":"DESC","sortField":"CREATED_DATE","pageNumber":2,"pageSize":100}`

**Comment by mteamwhy** [comment]
有辦法復現嗎

**Comment by nanoia** [comment]
> 有辦法復現嗎

反馈的问题似乎已经解决了，目前勾选分类后分页查询正常
