### ISSUE TITLE
个人页在部分场景下页面属性超出框架

### ISSUE THREAD

**Issue by mitlearn** [mteamwhy/mt-web-pre#44]
如题 个人签名在内容很长的情况下会导致框架超出
![无标题](https://github.com/mteamwhy/mt-web-pre/assets/64004444/af19cbb9-3ce1-4d43-a93c-3e45c011f327)

**Comment by jianglin8-hub** [comment]
用户id

**Comment by Mit2g** [comment]
> 用户id

uid 237634

**Comment by mitlearn** [comment]
> 用户id

uid 237634

**Comment by jakecreates1** [comment]
fixed.
