### ISSUE TITLE
种子文件名中的方头括号显示乱码

### ISSUE THREAD

**Issue by little6neko** [mteamwhy/mt-web-pre#5]
https://kp.m-team.cc/detail/767248
![image](https://github.com/mteamwhy/mt-web-pre/assets/34598766/6a3d84bd-3d0c-4db8-98d7-c21e766fa245)
![image](https://github.com/mteamwhy/mt-web-pre/assets/34598766/87cc9698-c393-4f86-8939-56454aa031c5)

**Comment by jianglin8-hub** [comment]
fixed.

修复仅对新上传生效。
