### ISSUE TITLE
種子無法下載

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#57]
https://kp.m-team.cc/detail/767468

**Comment by jeffery0513** [comment]
https://kp.m-team.cc/detail/483336
也是無法下載，點下載會出現unauthorised

**Comment by office365E5** [comment]
https://kp.m-team.cc/detail/767349
https://kp.m-team.cc/detail/766352
https://kp.m-team.cc/detail/765859
https://kp.m-team.cc/detail/765562

**Comment by haojp** [comment]
https://kp.m-team.cc/detail/610672
无法下载种子

**Comment by jianglin8-hub** [comment]
fixed.
