### ISSUE TITLE
界面显示异常

### ISSUE THREAD

**Issue by dizicheng** [mteamwhy/mt-web-pre#58]
![image](https://github.com/mteamwhy/mt-web-pre/assets/21209008/e936f39f-a767-4938-b179-12b32b0657c6)
按钮应当不可用

**Comment by dizicheng** [comment]
站内论坛用户名显示加载中
![image](https://github.com/mteamwhy/mt-web-pre/assets/21209008/8c251990-bb08-4b66-b8b2-ebf4184836a1)

**Comment by mteamwhy** [comment]
> 站内论坛用户名显示加载中 ![image](https://private-user-images.githubusercontent.com/21209008/316281705-8c251990-bb08-4b66-b8b2-ebf4184836a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTUxOTQsIm5iZiI6MTcxMTI1NDg5NCwicGF0aCI6Ii8yMTIwOTAwOC8zMTYyODE3MDUtOGMyNTE5OTAtYmIwOC00YjY2LWI4YjItZWJmNDE4NDgzNmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA0MzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNzhmOTc2ODA1OTRlMDRkNjk3NzViZTM4YWZhMTRhZDU3ODRmYjdmNWJiM2RiM2Q4MjA3MTJkYmQyODg4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhFTSKENFhPW0yrbPt8oZvWB7IvWaopdTJAcsvtqoh8)

論壇加載有問題

**Comment by dizicheng** [comment]
兑换按钮依旧可以使用
