### ISSUE TITLE
二次验证OTP功能异常

### ISSUE THREAD

**Issue by dizicheng** [mteamwhy/mt-web-pre#59]
使用账号密码登录时只显示邮箱验证码输入选项不显示二次验证码输入选项，升级前是有开启二次验证功能的，使用之前的cookie访问了控制台发现二级验证选项设置为了只使用密码登录，于是改成啟用密碼+動態驗證碼二級驗證，保存设置后登录界面出现了二次验证码输入选项，但是输入新保存OTP验证码显示登录失败，输入老OTP验证码显示登录成功。

**Comment by jianglin8-hub** [comment]
用户id

**Comment by dizicheng** [comment]
> 用户id
243859
dizicheng

**Comment by jianglin8-hub** [comment]
fixed
