### ISSUE TITLE
RSS订阅Enclosure类型错误导致qBittorrent无法订阅下载

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#61]
https://kp.m-team.cc/forum/t/62759

newline

订阅RSS返回的数据中，每个item的enclosure字段用于传递torrent下载链接，网站更新后，该字段的type传递的是application/octet-stream。

enclosure url="xxx" length="xxx" type="application/octet-stream"

但是qBittorrent的处理逻辑，其需要该处type字段为application/x-bittorrent，或者为空字符串，才会采纳该torrent下载链接。因此在当前网站返回的结果下，qBittorrent会回退到使用link标签里的url作为下载地址，当然就下载不到对应的torrent了。

else if (name == u"enclosure")
{
    if (xml.attributes().value(u"type"_s) == u"application/x-bittorrent")
        article[Article::KeyTorrentURL] = xml.attributes().value(u"url"_s).toString();
    else if (xml.attributes().value(u"type"_s).isEmpty())
        altTorrentUrl = xml.attributes().value(u"url"_s).toString();
}

以下引用https://www.bittorrent.org/beps/bep_0036.html：

enclosure

The enclosure tag MUST have a type attribute set to "application/x-bittorrent" and MUST store the torrent link in a url attribute. 

It MAY have a length attribute, which should indicate the size of the .torrent file, in bytes.

Example:

enclosure type="application/x-bittorrent" length="12216" url="http://featuredcontent.utorrent.com/torrents/WillisEarlBeal-BitTorrent.torrent"

建议最好将enclosure的type修改为application/x-bittorrent，避免RSS功能大面积失效。

**Comment by jianglin8-hub** [comment]
fixed
