### ISSUE TITLE
內站論壇帖子無法編輯

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#62]

**Comment by jianglin8-hub** [comment]
具体，哪个帖子，有没有报错信息

**Comment by bluegeo23** [comment]
具體帖子地址：https://kp.m-team.cc/forum/t/62795

編號：#288977

就是單純沒有編輯按鈕。

> 具体，哪个帖子，有没有报错信息

**Comment by zer0cod3** [comment]
> 具体，哪个帖子，有没有报错信息

自己发的贴子都不可编辑，找不到编辑的按钮或着说编辑的入口（没有报错信息），是不是把编辑自己帖子的功能给取消了？

**Comment by jianglin8-hub** [comment]
> 可编辑，找不到编辑的按钮或着说编辑的入

![image](https://github.com/mteamwhy/mt-web-pre/assets/16495257/d31c7dc5-0d55-49ec-b4a2-59c144839a26)
能看到？

**Comment by bluegeo23** [comment]
是說論壇的帖子：https://kp.m-team.cc/forum/t/62795

**Comment by zer0cod3** [comment]
> > 可编辑，找不到编辑的按钮或着说编辑的入
> 
> ![image](https://private-user-images.githubusercontent.com/16495257/316295489-d31c7dc5-0d55-49ec-b4a2-59c144839a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzMxMDMsIm5iZiI6MTcxMTI3MjgwMywicGF0aCI6Ii8xNjQ5NTI1Ny8zMTYyOTU0ODktZDMxYzdkYzUtMGQ1NS00OWVjLWI0YTItNTljMTQ0ODM5YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA5MzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhY2IyM2JhMWU3ZTMxMjFjNzE1Y2Y0ZDk1M2Y4NzYyNzQ4YjllY2ZhMjUwNWYxMjkwODU4YThkN2I3YmU5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-K0mNjkeTiFb4I2yqXtZ-ZyaH4wEXWdCNcegXSMQAk) 能看到？

说的是论坛里所发帖子的编辑，不是所发种子的编辑

**Comment by jianglin8-hub** [comment]
> 是說論壇的帖子：https://kp.m-team.cc/forum/t/62795

你看到的界面是怎样的

**Comment by zer0cod3** [comment]
> > 是說論壇的帖子：https://kp.m-team.cc/forum/t/62795
> 
> 你看到的界面是怎样的

看到【论坛】板块里自己所发的帖子（注意：不是【电影】等板块里自己所发的种子）没有编辑入口

**Comment by zer0cod3** [comment]
问题解决了
