### ISSUE TITLE
可以按照 做種/下載/已完成 的数量，对列表进行排序吗

### ISSUE THREAD

**Issue by ocian** [mteamwhy/mt-web-pre#65]
首先，这个是旧版 UI 存在的功能  
然后，已完成/下載 排序可以找出哪个种子能拿到更多的上传量，已完成/做種 排序可以找出同一个资源哪个种子在质量和下载支持上更好  
但是现在是没有这个功能的，希望能够补充

<img width="1425" alt="image" src="https://github.com/mteamwhy/mt-web-pre/assets/18749280/ae861c0f-74d1-4a1d-92fd-3fd50c929c5e">

**Comment by mteamwhy** [comment]
已有改造計劃
