### ISSUE TITLE
ipad iPhone等移动设备无法右击复制下载链接

### ISSUE THREAD

**Issue by HappyQuQu** [mteamwhy/mt-web-pre#69]
ipad iPhone等移动设备无法右击复制下载链接
![image](https://github.com/mteamwhy/mt-web-pre/assets/4098823/476f70a6-baee-44ee-b390-4abb2539b16a)

**Comment by mteamwhy** [comment]
這部份必須交由專業的移動端設計來處理

**Comment by mteamwhy** [comment]
請利用收藏功能rss下載
