### ISSUE TITLE
【發佈】种子时可选 [類別] 不全

### ISSUE THREAD

**Issue by zer0cod3** [mteamwhy/mt-web-pre#73]
【發佈】- [類別] 的下拉菜单里只有电影、影剧/综艺、Music、记录教育和演唱5个大类，没有动漫、体育、软体、游戏、电子书等在【綜合】的下拉菜单里出现的类别

**Comment by mteamwhy** [comment]
https://kp.m-team.cc/usercp?tab=laboratory
點選清理快取

**Comment by zer0cod3** [comment]
> https://kp.m-team.cc/usercp?tab=laboratory 點選清理快取

按照提示，在【控制台】-[實驗室]-網站快取 一项，多次点击“立即清理”按钮，完成之后【發佈】-[类别]的下拉菜单里并没有什么变化，仍然没有动漫、体育、软体、游戏、电子书等类别

**Comment by zer0cod3** [comment]
> https://kp.m-team.cc/usercp?tab=laboratory 點選清理快取

这个提示不好使。原来只有开启了成人内容，发种时才能出现动漫、体育、软体、游戏、电子书等可选类别。不过把这些类别和成人内容捆绑在一起属实没啥道理。好在管理员终于修正了这个问题。
