### ISSUE TITLE
新网站搜索结果页面不显示已经下载过的种子和百分比了，另外，也无法根据种子发布者名字来进行搜索了

### ISSUE THREAD

**Issue by zoukai3412085** [mteamwhy/mt-web-pre#77]
突然发现新网站不会用了， 我搜索关键词，好像右侧不现实已经下载过或者正在下载的条目的百分比了

另外，好像也没办法搜索发布者的姓名来筛选资源了，突然感觉不会用了

**Comment by mteamwhy** [comment]
发布者的姓名来筛选
這部份不會開放
