### ISSUE TITLE
限免时间加上分钟数显示

### ISSUE THREAD

**Issue by ccc-3po** [mteamwhy/mt-web-pre#78]
目前限免资源仅显示小时，希望添加分钟数显示。
![image](https://github.com/mteamwhy/mt-web-pre/assets/44689813/7d0463d0-dcec-4085-ad89-4f70bbcd141a)

**Comment by BlueSkyClouds** [comment]
鼠标触碰可显示具体到期时间 精确到秒

**Comment by ccc-3po** [comment]
@BlueSkyClouds @mteamwhy 感谢两位。后期如果有时间的话希望可以把剩余时间直接完整展示出来。

**Comment by BlueSkyClouds** [comment]
你是想显示剩余1小时1分钟还是剩余时间<1小时的时候显示分钟，如果是后者，是已有的功能

**Comment by ccc-3po** [comment]
> 你是想显示剩余1小时1分钟还是剩余时间<1小时的时候显示分钟，如果是后者，是已有的功能

前者（Free [剩余时间：1小时1分钟]），进行倒计时实时显示，随着页面刷新，数字也会变动。
