### ISSUE TITLE
综合栏目下 日剧 美剧等选单无法生效

### ISSUE THREAD

**Issue by jmdweem** [mteamwhy/mt-web-pre#79]
![image](https://github.com/mteamwhy/mt-web-pre/assets/90380039/a13cd453-16b4-4bc3-ba45-221dfd506863)
目前观察到在综合->剧集栏目下选择对应地区的剧集时，跳转出来的结果是错误的
例如，图中我选择了美剧，但下方筛选出来的内容却包含了港剧 韩剧 日剧等等，并没有起到筛选的作用

**Comment by mteamwhy** [comment]
https://kp.m-team.cc/usercp?tab=laboratory
點選清理快取
