### ISSUE TITLE
使用163等禁用郵箱捐贈註冊時提示語不正確

### ISSUE THREAD

**Issue by bluegeo23** [mteamwhy/mt-web-pre#80]
![image](https://github.com/mteamwhy/mt-web-pre/assets/164606755/90e40d11-7516-4a78-9df9-1fe0877a0318)

此時應提示“僅允許使用qq/google郵箱註冊”。

**Comment by mteamwhy** [comment]
我把設定關掉了，現在打開了

**Comment by jianglin8-hub** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/16495257/66b836ba-2913-443d-8c0d-45f9eaaca270)

无此问题
