### ISSUE TITLE
种子重复发布

### ISSUE THREAD

**Issue by BlueSkyClouds** [mteamwhy/mt-web-pre#81]
一个应该是在升级前自动发种机发的，另一个在升级后自动发种机又发了一遍 显示错误 而且上传时未提示重复种子
https://kp.m-team.cc/detail/767553
https://kp.m-team.cc/detail/767147

![image](https://github.com/mteamwhy/mt-web-pre/assets/39831773/5d68f546-405a-47d4-aaad-7837f9179711)

**Comment by jianglin8-hub** [comment]
fixed
