### ISSUE TITLE
魔力系統兌換魔力問題

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#82]
https://kp.m-team.cc/profile/detail/266261

該用戶分享率少於5，但不能兌換上傳

**Comment by jianglin8-hub** [comment]
具体点，有什么提示

**Comment by dizicheng** [comment]
和这个恰恰相反
#58

**Comment by ChenDY2233** [comment]
![image](https://github.com/mteamwhy/mt-web-pre/assets/39426660/6d72878e-050b-4133-9558-b83ea3604571)

**Comment by dizicheng** [comment]
> ![image](https://github.com/mteamwhy/mt-web-pre/assets/39426660/6d72878e-050b-4133-9558-b83ea3604571)
> 

好的，看起来是已经修复了，我不敢点。

**Comment by ChenDY2233** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39426660/316492989-6d72878e-050b-4133-9558-b83ea3604571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjk5OTksIm5iZiI6MTcxMTM2OTY5OSwicGF0aCI6Ii8zOTQyNjY2MC8zMTY0OTI5ODktNmQ3Mjg3OGUtMDUwYi00MTMzLTk1NTgtYjgzZWEzNjA0NTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGQ3OTIxYWE2ODdlNzcyNGNjZjA4Njg1NjE2N2E2OWFmZDkzZWMzOTBlYjI1NTk3YTc2NjJkN2VhZWM2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_dofH1znGfKyG6jvtkSGhzRAu1EtS-iJM9Fz3hmiAY)
> 
> 好的，看起来是已经修复了，我不敢点。

没修复呢，现在就是截图中的样子

**Comment by dizicheng** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/39426660/316492989-6d72878e-050b-4133-9558-b83ea3604571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjk5OTksIm5iZiI6MTcxMTM2OTY5OSwicGF0aCI6Ii8zOTQyNjY2MC8zMTY0OTI5ODktNmQ3Mjg3OGUtMDUwYi00MTMzLTk1NTgtYjgzZWEzNjA0NTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGQ3OTIxYWE2ODdlNzcyNGNjZjA4Njg1NjE2N2E2OWFmZDkzZWMzOTBlYjI1NTk3YTc2NjJkN2VhZWM2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_dofH1znGfKyG6jvtkSGhzRAu1EtS-iJM9Fz3hmiAY)
> > 
> > 好的，看起来是已经修复了，我不敢点。
> 
> 没修复呢，现在就是截图中的样子

你看屏幕的正上方显示最大可兑换0

**Comment by jianglin8-hub** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/39426660/316492989-6d72878e-050b-4133-9558-b83ea3604571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjk5OTksIm5iZiI6MTcxMTM2OTY5OSwicGF0aCI6Ii8zOTQyNjY2MC8zMTY0OTI5ODktNmQ3Mjg3OGUtMDUwYi00MTMzLTk1NTgtYjgzZWEzNjA0NTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGQ3OTIxYWE2ODdlNzcyNGNjZjA4Njg1NjE2N2E2OWFmZDkzZWMzOTBlYjI1NTk3YTc2NjJkN2VhZWM2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_dofH1znGfKyG6jvtkSGhzRAu1EtS-iJM9Fz3hmiAY)
> > > 
> > > 
> > > 好的，看起来是已经修复了，我不敢点。
> > 
> > 
> > 没修复呢，现在就是截图中的样子
> 
> 你看屏幕的正上方显示最大可兑换0

前端數據存在延遲，以接口爲準吧

**Comment by mteamwhy** [comment]
fix
