### ISSUE TITLE
豆瓣相同版本不会显示

### ISSUE THREAD

**Issue by BlueSkyClouds** [mteamwhy/mt-web-pre#87]

**Comment by jianglin8-hub** [comment]
哪个链接没提示

**Comment by BlueSkyClouds** [comment]
只填写了豆瓣链接的情况下，相同版本按钮都没有

**Comment by BlueSkyClouds** [comment]
> 哪个链接没提示

如https://kp.m-team.cc/detail/769023  只填写了豆瓣链接
而另一个https://kp.m-team.cc/detail/482317  同时填写了豆瓣和IMDB   
769023  就不会显示相同版本

**Comment by jianglin8-hub** [comment]
> > 哪个链接没提示
> 
> 如https://kp.m-team.cc/detail/769023 只填写了豆瓣链接 而另一个https://kp.m-team.cc/detail/482317 同时填写了豆瓣和IMDB 769023 就不会显示其他版本

符合预期，douban只查douban，imdb同理，没有imdb 与douban的对应表
