### ISSUE TITLE
EU论坛搜索功能异常

### ISSUE THREAD

**Issue by PFCraft-box** [mteamwhy/mt-web-pre#92]
EU论坛搜索任意关键词，响应数据不符合预期
复现流程
1.输入"邀请求助"进行搜索
2.响应数据包含其他无关条目
为确保安全性，已隐去站点信息
![image](https://github.com/mteamwhy/mt-web-pre/assets/47564241/1d0e53db-69bc-43f4-8e91-2cfed2496e13)

**Comment by BlueSkyClouds** [comment]
待修复

**Comment by jianglin8-hub** [comment]
fixed
