### ISSUE TITLE
排行榜改造計劃

### ISSUE THREAD

**Issue by mteamwhy** [mteamwhy/mt-web-pre#99]
根據種子分類來實施各分類底下的種子熱門排行

導航列如下

![圖片](https://github.com/mteamwhy/mt-web-pre/assets/30530524/4f954a4c-bd20-4fcc-879a-b12e546fa145)

點選該分類即出現該分類底下前100種子(可切換依 做種/下載/完成)，更新時間為60分鐘一次

**Comment by jianglin8-hub** [comment]
可行

**Comment by mteamwhy** [comment]
同分類底下增加
有史以來/月排行/周排行

**Comment by jianglin8-hub** [comment]
> 同分類底下增加
> 有史以來/月排行/周排行

本次只实现实时排行，历史排行暂不做

**Comment by jianglin8-hub** [comment]
@mteamwhy https://kp.m-team.cc/rankings
